"""Per-exercise icon paths (relative to /static), generated from
workout_emojis.zip -- a 227-icon flat 2D vector illustration pack covering
every exercise in workout_library.EXERCISE_CATEGORIES.

Regenerate by re-running the manifest.json -> dict conversion this file
was built from if the icon pack is ever replaced.
"""

EXERCISE_ICONS = {
    # ---------- Chest ----------
    "Flat Bench Press": "exercise_icons/chest/001_flat_bench_press.svg",
    "Incline Bench Press": "exercise_icons/chest/002_incline_bench_press.svg",
    "Decline Bench Press": "exercise_icons/chest/003_decline_bench_press.svg",
    "Dumbbell Bench Press": "exercise_icons/chest/004_dumbbell_bench_press.svg",
    "Incline Dumbbell Press": "exercise_icons/chest/005_incline_dumbbell_press.svg",
    "Decline Dumbbell Press": "exercise_icons/chest/006_decline_dumbbell_press.svg",
    "Floor Press": "exercise_icons/chest/007_floor_press.svg",
    "Chest Fly": "exercise_icons/chest/008_chest_fly.svg",
    "Cable Crossover": "exercise_icons/chest/009_cable_crossover.svg",
    "Pec Deck": "exercise_icons/chest/010_pec_deck.svg",
    "Push-Up": "exercise_icons/chest/011_push_up.svg",
    "Incline Push-Up": "exercise_icons/chest/012_incline_push_up.svg",
    "Decline Push-Up": "exercise_icons/chest/013_decline_push_up.svg",
    "Dips": "exercise_icons/chest/014_dips.svg",
    "Landmine Press": "exercise_icons/chest/015_landmine_press.svg",
    "Resistance Band Chest Press": "exercise_icons/chest/016_resistance_band_chest_press.svg",
    # ---------- Back ----------
    "Wide-Grip Lat Pulldown": "exercise_icons/back/017_wide_grip_lat_pulldown.svg",
    "Close-Grip Lat Pulldown": "exercise_icons/back/018_close_grip_lat_pulldown.svg",
    "Straight-Arm Pulldown": "exercise_icons/back/019_straight_arm_pulldown.svg",
    "Pull-Up": "exercise_icons/back/020_pull_up.svg",
    "Chin-Up": "exercise_icons/back/021_chin_up.svg",
    "Bent-Over Row": "exercise_icons/back/022_bent_over_row.svg",
    "Seated Cable Row": "exercise_icons/back/023_seated_cable_row.svg",
    "Dumbbell Row": "exercise_icons/back/024_dumbbell_row.svg",
    "Single-Arm Dumbbell Row": "exercise_icons/back/025_single_arm_dumbbell_row.svg",
    "T-Bar Row": "exercise_icons/back/026_t_bar_row.svg",
    "Inverted Row": "exercise_icons/back/027_inverted_row.svg",
    "Resistance Band Row": "exercise_icons/back/028_resistance_band_row.svg",
    "Renegade Row": "exercise_icons/back/029_renegade_row.svg",
    "Deadlift": "exercise_icons/back/030_deadlift.svg",
    "Sumo Deadlift": "exercise_icons/back/031_sumo_deadlift.svg",
    "Rack Pull": "exercise_icons/back/032_rack_pull.svg",
    "Romanian Deadlift (RDL)": "exercise_icons/back/033_romanian_deadlift_rdl.svg",
    "Dumbbell Romanian Deadlift": "exercise_icons/back/034_dumbbell_romanian_deadlift.svg",
    "Stiff-Leg Deadlift (SLDL)": "exercise_icons/back/035_stiff_leg_deadlift_sldl.svg",
    "Good Morning": "exercise_icons/back/036_good_morning.svg",
    # ---------- Shoulders ----------
    "Shoulder Press": "exercise_icons/shoulders/037_shoulder_press.svg",
    "Overhead Press": "exercise_icons/shoulders/038_overhead_press.svg",
    "Arnold Press": "exercise_icons/shoulders/039_arnold_press.svg",
    "Lateral Raise": "exercise_icons/shoulders/040_lateral_raise.svg",
    "Cable Lateral Raise": "exercise_icons/shoulders/041_cable_lateral_raise.svg",
    "Front Raise": "exercise_icons/shoulders/042_front_raise.svg",
    "Rear Delt Fly": "exercise_icons/shoulders/043_rear_delt_fly.svg",
    "Face Pull": "exercise_icons/shoulders/044_face_pull.svg",
    "Resistance Band Face Pull": "exercise_icons/shoulders/045_resistance_band_face_pull.svg",
    "Upright Row": "exercise_icons/shoulders/046_upright_row.svg",
    "Shrug": "exercise_icons/shoulders/047_shrug.svg",
    "Pike Push-Up": "exercise_icons/shoulders/048_pike_push_up.svg",
    # ---------- Arms ----------
    "Bicep Curl": "exercise_icons/arms/049_bicep_curl.svg",
    "Barbell Bicep Curl": "exercise_icons/arms/050_barbell_bicep_curl.svg",
    "EZ-Bar Bicep Curl": "exercise_icons/arms/051_ez_bar_bicep_curl.svg",
    "Resistance Band Bicep Curl": "exercise_icons/arms/052_resistance_band_bicep_curl.svg",
    "Hammer Curl": "exercise_icons/arms/053_hammer_curl.svg",
    "Preacher Curl": "exercise_icons/arms/054_preacher_curl.svg",
    "Concentration Curl": "exercise_icons/arms/055_concentration_curl.svg",
    "Cable Curl": "exercise_icons/arms/056_cable_curl.svg",
    "Spider Curl": "exercise_icons/arms/057_spider_curl.svg",
    "Zottman Curl": "exercise_icons/arms/058_zottman_curl.svg",
    "Tricep Pushdown": "exercise_icons/arms/059_tricep_pushdown.svg",
    "Tricep Extension": "exercise_icons/arms/060_tricep_extension.svg",
    "Overhead Tricep Extension": "exercise_icons/arms/061_overhead_tricep_extension.svg",
    "Barbell Skull Crusher": "exercise_icons/arms/062_barbell_skull_crusher.svg",
    "Skull Crusher": "exercise_icons/arms/063_skull_crusher.svg",
    "Close-Grip Bench Press": "exercise_icons/arms/064_close_grip_bench_press.svg",
    "Diamond Push-Up": "exercise_icons/arms/065_diamond_push_up.svg",
    "Bench Dip": "exercise_icons/arms/066_bench_dip.svg",
    "Cable Kickback": "exercise_icons/arms/067_cable_kickback.svg",
    # ---------- Legs ----------
    "Squat": "exercise_icons/legs/068_squat.svg",
    "Dumbbell Squat": "exercise_icons/legs/069_dumbbell_squat.svg",
    "Front Squat": "exercise_icons/legs/070_front_squat.svg",
    "Goblet Squat": "exercise_icons/legs/071_goblet_squat.svg",
    "Sumo Squat": "exercise_icons/legs/072_sumo_squat.svg",
    "Box Squat": "exercise_icons/legs/073_box_squat.svg",
    "Pistol Squat": "exercise_icons/legs/074_pistol_squat.svg",
    "Leg Press": "exercise_icons/legs/075_leg_press.svg",
    "Hack Squat": "exercise_icons/legs/076_hack_squat.svg",
    "Leg Extension": "exercise_icons/legs/077_leg_extension.svg",
    "Lying Leg Curl Machine": "exercise_icons/legs/078_lying_leg_curl_machine.svg",
    "Seated Leg Curl": "exercise_icons/legs/079_seated_leg_curl.svg",
    "Nordic Hamstring Curl": "exercise_icons/legs/080_nordic_hamstring_curl.svg",
    "Walking Lunge": "exercise_icons/legs/081_walking_lunge.svg",
    "Reverse Lunge": "exercise_icons/legs/082_reverse_lunge.svg",
    "Bulgarian Split Squat": "exercise_icons/legs/083_bulgarian_split_squat.svg",
    "Step-Up": "exercise_icons/legs/084_step_up.svg",
    "Hip Thrust": "exercise_icons/legs/085_hip_thrust.svg",
    "Barbell Hip Thrust": "exercise_icons/legs/086_barbell_hip_thrust.svg",
    "Glute Bridge": "exercise_icons/legs/087_glute_bridge.svg",
    "Hip Abduction Machine": "exercise_icons/legs/088_hip_abduction_machine.svg",
    "Hip Adduction Machine": "exercise_icons/legs/089_hip_adduction_machine.svg",
    "Calf Raise": "exercise_icons/legs/090_calf_raise.svg",
    "Seated Calf Raise": "exercise_icons/legs/091_seated_calf_raise.svg",
    "Sissy Squat": "exercise_icons/legs/092_sissy_squat.svg",
    # ---------- Core ----------
    "Plank": "exercise_icons/core/093_plank.svg",
    "Side Plank": "exercise_icons/core/094_side_plank.svg",
    "Crunch": "exercise_icons/core/095_crunch.svg",
    "Bicycle Crunch": "exercise_icons/core/096_bicycle_crunch.svg",
    "Cable Crunch": "exercise_icons/core/097_cable_crunch.svg",
    "Sit-Up": "exercise_icons/core/098_sit_up.svg",
    "V-Up": "exercise_icons/core/099_v_up.svg",
    "Hanging Leg Raise": "exercise_icons/core/100_hanging_leg_raise.svg",
    "Ab Wheel Rollout": "exercise_icons/core/101_ab_wheel_rollout.svg",
    "Cable Woodchopper": "exercise_icons/core/102_cable_woodchopper.svg",
    "Russian Twist": "exercise_icons/core/103_russian_twist.svg",
    "Dead Bug": "exercise_icons/core/104_dead_bug.svg",
    "Mountain Climber": "exercise_icons/core/105_mountain_climber.svg",
    # ---------- Full Body - Conditioning ----------
    "Kettlebell Swing": "exercise_icons/full_body_conditioning/106_kettlebell_swing.svg",
    "Farmer's Carry": "exercise_icons/full_body_conditioning/107_farmer_s_carry.svg",
    "Thruster": "exercise_icons/full_body_conditioning/108_thruster.svg",
    "Burpee": "exercise_icons/full_body_conditioning/109_burpee.svg",
    "Devil Press": "exercise_icons/full_body_conditioning/110_devil_press.svg",
    "Clean and Jerk": "exercise_icons/full_body_conditioning/111_clean_and_jerk.svg",
    "Snatch": "exercise_icons/full_body_conditioning/112_snatch.svg",
    "Wall Ball Shot": "exercise_icons/full_body_conditioning/113_wall_ball_shot.svg",
    "Sled Push": "exercise_icons/full_body_conditioning/114_sled_push.svg",
    "Sled Pull": "exercise_icons/full_body_conditioning/115_sled_pull.svg",
    "Box Jump Over": "exercise_icons/full_body_conditioning/116_box_jump_over.svg",
    "Rowing Machine Intervals": "exercise_icons/full_body_conditioning/117_rowing_machine_intervals.svg",
    "Assault Bike Intervals": "exercise_icons/full_body_conditioning/118_assault_bike_intervals.svg",
    # ---------- Mobility & Flexibility ----------
    "World's Greatest Stretch": "exercise_icons/mobility_and_flexibility/119_world_s_greatest_stretch.svg",
    "Cat-Cow Stretch": "exercise_icons/mobility_and_flexibility/120_cat_cow_stretch.svg",
    "Thoracic Spine Rotation": "exercise_icons/mobility_and_flexibility/121_thoracic_spine_rotation.svg",
    "90/90 Hip Stretch": "exercise_icons/mobility_and_flexibility/122_90_90_hip_stretch.svg",
    "Deep Squat Hold": "exercise_icons/mobility_and_flexibility/123_deep_squat_hold.svg",
    "Cossack Squat": "exercise_icons/mobility_and_flexibility/124_cossack_squat.svg",
    "Hip Flexor Stretch": "exercise_icons/mobility_and_flexibility/125_hip_flexor_stretch.svg",
    "Pigeon Pose": "exercise_icons/mobility_and_flexibility/126_pigeon_pose.svg",
    "Downward Dog": "exercise_icons/mobility_and_flexibility/127_downward_dog.svg",
    "Shoulder Dislocates": "exercise_icons/mobility_and_flexibility/128_shoulder_dislocates.svg",
    "Arm Circles": "exercise_icons/mobility_and_flexibility/129_arm_circles.svg",
    "Band Pull-Apart": "exercise_icons/mobility_and_flexibility/130_band_pull_apart.svg",
    "Wall Slides": "exercise_icons/mobility_and_flexibility/131_wall_slides.svg",
    "Leg Swings": "exercise_icons/mobility_and_flexibility/132_leg_swings.svg",
    "Walking Knee Hug": "exercise_icons/mobility_and_flexibility/133_walking_knee_hug.svg",
    "Spiderman Lunge with Reach": "exercise_icons/mobility_and_flexibility/134_spiderman_lunge_with_reach.svg",
    "Standing Quad Stretch": "exercise_icons/mobility_and_flexibility/135_standing_quad_stretch.svg",
    "Ankle Mobility Drill": "exercise_icons/mobility_and_flexibility/136_ankle_mobility_drill.svg",
    "Scorpion Stretch": "exercise_icons/mobility_and_flexibility/137_scorpion_stretch.svg",
    "Foam Rolling": "exercise_icons/mobility_and_flexibility/138_foam_rolling.svg",
    # ---------- Athletic - Speed & Agility ----------
    "Sprint Starts": "exercise_icons/athletic_speed_and_agility/139_sprint_starts.svg",
    "Flying Sprints": "exercise_icons/athletic_speed_and_agility/140_flying_sprints.svg",
    "Hill Sprints": "exercise_icons/athletic_speed_and_agility/141_hill_sprints.svg",
    "Resisted Sprint (Sled Push)": "exercise_icons/athletic_speed_and_agility/142_resisted_sprint_sled_push.svg",
    "Sled Drag": "exercise_icons/athletic_speed_and_agility/143_sled_drag.svg",
    "Box Jump": "exercise_icons/athletic_speed_and_agility/144_box_jump.svg",
    "Depth Jump": "exercise_icons/athletic_speed_and_agility/145_depth_jump.svg",
    "Broad Jump": "exercise_icons/athletic_speed_and_agility/146_broad_jump.svg",
    "Lateral Bound": "exercise_icons/athletic_speed_and_agility/147_lateral_bound.svg",
    "Single-Leg Bound": "exercise_icons/athletic_speed_and_agility/148_single_leg_bound.svg",
    "Agility Ladder Drills": "exercise_icons/athletic_speed_and_agility/149_agility_ladder_drills.svg",
    "Cone Shuttle Run": "exercise_icons/athletic_speed_and_agility/150_cone_shuttle_run.svg",
    "5-10-5 Pro Agility Drill": "exercise_icons/athletic_speed_and_agility/151_5_10_5_pro_agility_drill.svg",
    "T-Drill": "exercise_icons/athletic_speed_and_agility/152_t_drill.svg",
    "Reactive Ball Drop Drill": "exercise_icons/athletic_speed_and_agility/153_reactive_ball_drop_drill.svg",
    "Medicine Ball Rotational Throw": "exercise_icons/athletic_speed_and_agility/154_medicine_ball_rotational_throw.svg",
    "Medicine Ball Chest Pass": "exercise_icons/athletic_speed_and_agility/155_medicine_ball_chest_pass.svg",
    "Medicine Ball Slam": "exercise_icons/athletic_speed_and_agility/156_medicine_ball_slam.svg",
    "Jump Rope": "exercise_icons/athletic_speed_and_agility/157_jump_rope.svg",
    "High Knees": "exercise_icons/athletic_speed_and_agility/158_high_knees.svg",
    "Butt Kicks": "exercise_icons/athletic_speed_and_agility/159_butt_kicks.svg",
    "A-Skip": "exercise_icons/athletic_speed_and_agility/160_a_skip.svg",
    "B-Skip": "exercise_icons/athletic_speed_and_agility/161_b_skip.svg",
    "Bounding": "exercise_icons/athletic_speed_and_agility/162_bounding.svg",
    "Plyo Push-Up": "exercise_icons/athletic_speed_and_agility/163_plyo_push_up.svg",
    "Squat Jump": "exercise_icons/athletic_speed_and_agility/164_squat_jump.svg",
    "Tuck Jump": "exercise_icons/athletic_speed_and_agility/165_tuck_jump.svg",
    "Lateral Skater Jump": "exercise_icons/athletic_speed_and_agility/166_lateral_skater_jump.svg",
    # ---------- Functional - Real-World Strength ----------
    "Suitcase Carry": "exercise_icons/functional_real_world_strength/167_suitcase_carry.svg",
    "Overhead Carry": "exercise_icons/functional_real_world_strength/168_overhead_carry.svg",
    "Sandbag Carry": "exercise_icons/functional_real_world_strength/169_sandbag_carry.svg",
    "Sandbag Clean": "exercise_icons/functional_real_world_strength/170_sandbag_clean.svg",
    "Sandbag Shouldering": "exercise_icons/functional_real_world_strength/171_sandbag_shouldering.svg",
    "Zercher Carry": "exercise_icons/functional_real_world_strength/172_zercher_carry.svg",
    "Yoke Walk": "exercise_icons/functional_real_world_strength/173_yoke_walk.svg",
    "Turkish Get-Up": "exercise_icons/functional_real_world_strength/174_turkish_get_up.svg",
    "Bear Crawl": "exercise_icons/functional_real_world_strength/175_bear_crawl.svg",
    "Crawling Drill": "exercise_icons/functional_real_world_strength/176_crawling_drill.svg",
    "Sit-to-Stand": "exercise_icons/functional_real_world_strength/177_sit_to_stand.svg",
    "Floor-to-Stand Get-Up": "exercise_icons/functional_real_world_strength/178_floor_to_stand_get_up.svg",
    "Loaded Stair Climb": "exercise_icons/functional_real_world_strength/179_loaded_stair_climb.svg",
    "Tire Flip": "exercise_icons/functional_real_world_strength/180_tire_flip.svg",
    "Deadlift to Shoulder (Sandbag)": "exercise_icons/functional_real_world_strength/181_deadlift_to_shoulder_sandbag.svg",
    "Zercher Squat": "exercise_icons/functional_real_world_strength/182_zercher_squat.svg",
    "Suitcase Deadlift": "exercise_icons/functional_real_world_strength/183_suitcase_deadlift.svg",
    "Single-Arm Farmer's Carry": "exercise_icons/functional_real_world_strength/184_single_arm_farmer_s_carry.svg",
    "Wheelbarrow Carry": "exercise_icons/functional_real_world_strength/185_wheelbarrow_carry.svg",
    "Log Press": "exercise_icons/functional_real_world_strength/186_log_press.svg",
    "Atlas Stone Lift": "exercise_icons/functional_real_world_strength/187_atlas_stone_lift.svg",
    "Keg Carry": "exercise_icons/functional_real_world_strength/188_keg_carry.svg",
    # ---------- Balance & Stability ----------
    "Single-Leg Balance Hold": "exercise_icons/balance_and_stability/189_single_leg_balance_hold.svg",
    "Single-Leg Romanian Deadlift": "exercise_icons/balance_and_stability/190_single_leg_romanian_deadlift.svg",
    "Bosu Ball Squat": "exercise_icons/balance_and_stability/191_bosu_ball_squat.svg",
    "Bosu Ball Balance Hold": "exercise_icons/balance_and_stability/192_bosu_ball_balance_hold.svg",
    "Single-Leg Box Step-Down": "exercise_icons/balance_and_stability/193_single_leg_box_step_down.svg",
    "Tandem Stance Hold": "exercise_icons/balance_and_stability/194_tandem_stance_hold.svg",
    "Heel-to-Toe Walk": "exercise_icons/balance_and_stability/195_heel_to_toe_walk.svg",
    "Single-Leg Deadlift Reach": "exercise_icons/balance_and_stability/196_single_leg_deadlift_reach.svg",
    "Stability Ball Plank": "exercise_icons/balance_and_stability/197_stability_ball_plank.svg",
    "Stability Ball Hamstring Curl": "exercise_icons/balance_and_stability/198_stability_ball_hamstring_curl.svg",
    "Single-Leg Glute Bridge": "exercise_icons/balance_and_stability/199_single_leg_glute_bridge.svg",
    "Balance Beam Walk": "exercise_icons/balance_and_stability/200_balance_beam_walk.svg",
    "Slackline Balance": "exercise_icons/balance_and_stability/201_slackline_balance.svg",
    "Single-Leg Hop and Stick": "exercise_icons/balance_and_stability/202_single_leg_hop_and_stick.svg",
    "Wobble Board Balance": "exercise_icons/balance_and_stability/203_wobble_board_balance.svg",
    "Pallof Press": "exercise_icons/balance_and_stability/204_pallof_press.svg",
    "Standing Y-Balance Reach": "exercise_icons/balance_and_stability/205_standing_y_balance_reach.svg",
    # ---------- Prenatal - Low-Impact ----------
    "Prenatal Cat-Cow Stretch": "exercise_icons/prenatal_low_impact/206_prenatal_cat_cow_stretch.svg",
    "Pelvic Tilt": "exercise_icons/prenatal_low_impact/207_pelvic_tilt.svg",
    "Kegel Exercise": "exercise_icons/prenatal_low_impact/208_kegel_exercise.svg",
    "Bird Dog": "exercise_icons/prenatal_low_impact/209_bird_dog.svg",
    "Wall Push-Up": "exercise_icons/prenatal_low_impact/210_wall_push_up.svg",
    "Seated Row (Band)": "exercise_icons/prenatal_low_impact/211_seated_row_band.svg",
    "Standing Band Row": "exercise_icons/prenatal_low_impact/212_standing_band_row.svg",
    "Side-Lying Leg Lift": "exercise_icons/prenatal_low_impact/213_side_lying_leg_lift.svg",
    "Side-Lying Clam Shell": "exercise_icons/prenatal_low_impact/214_side_lying_clam_shell.svg",
    "Prenatal Squat (Supported)": "exercise_icons/prenatal_low_impact/215_prenatal_squat_supported.svg",
    "Chair Squat": "exercise_icons/prenatal_low_impact/216_chair_squat.svg",
    "Wall Sit (Light)": "exercise_icons/prenatal_low_impact/217_wall_sit_light.svg",
    "Standing Bicep Curl (Light Dumbbell)": "exercise_icons/prenatal_low_impact/218_standing_bicep_curl_light_dumbbell.svg",
    "Seated Shoulder Press (Light)": "exercise_icons/prenatal_low_impact/219_seated_shoulder_press_light.svg",
    "Prenatal Walking": "exercise_icons/prenatal_low_impact/220_prenatal_walking.svg",
    "Stationary Cycling (Light)": "exercise_icons/prenatal_low_impact/221_stationary_cycling_light.svg",
    "Water Aerobics": "exercise_icons/prenatal_low_impact/222_water_aerobics.svg",
    "Prenatal Yoga Flow": "exercise_icons/prenatal_low_impact/223_prenatal_yoga_flow.svg",
    "Standing Pelvic Circles": "exercise_icons/prenatal_low_impact/224_standing_pelvic_circles.svg",
    "Modified Side Plank (Knee Down)": "exercise_icons/prenatal_low_impact/225_modified_side_plank_knee_down.svg",
    "Seated Leg Extension (Light)": "exercise_icons/prenatal_low_impact/226_seated_leg_extension_light.svg",
    "Ankle Pumps": "exercise_icons/prenatal_low_impact/227_ankle_pumps.svg",
}
