"""Search-depth variations: a second additive catalog on top of
extra_exercises.py.

Why this exists: the analyze page's exercise picker (and the workout
logger's, which shares the same library) is a plain substring search over
WORKOUT_EXERCISES, so the number of suggestions a lifter sees for "dip",
"step-up" or "hip thrust" is exactly however many names happen to contain
that word -- and for a lot of common movements that was 2-8, which reads as
"the app doesn't know this exercise". This module fills those thin searches
out to roughly fifteen genuine variations each, so a common movement typed
into the picker comes back with a full, useful list.

Shape is identical to extra_exercises.EXTRA_EXERCISES (name, category,
emoji, location, unilateral, description) and it is merged the same way, so
categories, locations, unilateral tagging and the how-to notes in
exercise_details.py all pick these up for free.

A few movements genuinely don't have fifteen named variants (nobody does
fifteen distinct Good Mornings), so those land at whatever number is real
rather than being padded out with invented names.

Like extra_exercises.py, this module imports nothing from the rest of the
app, so it can't create an import cycle.
"""

# (name, emoji, location, unilateral, description)
_BY_CATEGORY = {
    "Chest": [
        ("Paused Bench Press", "\U0001F3CB️", "gym", False, ["A barbell bench press held motionless on the chest for a full second before pressing.", "Killing the stretch reflex builds raw strength off the bottom; stay tight through the pause."]),
        ("Feet-Up Bench Press", "\U0001F3CB️", "gym", False, ["A bench press with the feet lifted onto the bench instead of planted.", "Removing leg drive forces the chest and shoulders to do all the work and teaches a properly braced torso."]),
        ("Neutral-Grip Dumbbell Bench Press", "\U0001F3CB️", "both", False, ["A dumbbell bench press with the palms facing each other throughout.", "The neutral grip is much kinder to cranky shoulders while still loading the chest and triceps hard."]),
        ("Single-Arm Dumbbell Bench Press", "\U0001F3CB️", "both", True, ["A dumbbell bench press done one arm at a time.", "The offset load turns it into a serious anti-rotation core exercise too; keep the hips square to the bench."]),
        ("Close-Grip Incline Bench Press", "\U0001F3CB️", "gym", False, ["An incline barbell press with the hands about shoulder-width apart.", "Shifts load onto the upper chest and triceps; keep the elbows tucked and press toward the collarbone."]),
        ("Guillotine Bench Press", "\U0001F3CB️", "gym", False, ["A flared-elbow bench press lowered toward the neck rather than the sternum, biasing the upper chest.", "Go light, use a spotter, and never let the bar drop."]),
        ("Parallel Bar Dip", "\U0001F3CB️", "both", False, ["A bodyweight dip on parallel bars, lowering until the upper arms are roughly parallel to the floor.", "The baseline dip; keep the shoulders down and press back to a soft lockout."]),
        ("Straight-Bar Dip", "\U0001F3CB️", "both", False, ["A dip on a single straight bar, which forces the body to lean back over the bar.", "Harder on the shoulders and much more of a chest and core challenge; build up slowly."]),
        ("Banded Dip", "\U0001F3CB️", "both", False, ["A dip with a resistance band looped under the knees to take some bodyweight off.", "The best way to own the full range while you build toward unassisted reps."]),
        ("Weighted Ring Dip", "\U0001F3CB️", "gym", False, ["A ring dip with a dip belt or weight vest added.", "Ring instability plus real external load is about as hard as pressing gets; keep the rings pinned to your sides."]),
        ("Feet-Elevated Bench Dip", "\U0001F4AA", "home", False, ["A bench dip with the heels up on a second bench or chair.", "Elevating the feet loads the triceps much harder than the floor version; keep the hips close to the bench."]),
        ("Slow-Negative Dip", "\U0001F3CB️", "both", False, ["A dip lowered over three to five seconds, then reset by stepping or jumping back to the top.", "Eccentric-only work builds the strength for full reps faster than assisted ones."]),
        ("Chest-Lean Dip", "\U0001F3CB️", "both", False, ["A dip with a deliberate forward torso lean and flared elbows to bias the chest over the triceps.", "Let the chest travel toward the hands and stop when the shoulders feel the stretch."]),
        ("Upright Dip (Tricep Focus)", "\U0001F4AA", "both", False, ["A dip kept as vertical as possible with the elbows tucked to your sides.", "The upright torso hands the work to the triceps; a great heavy tricep builder."]),
        ("Dip Support Hold", "\U0001F9D8", "both", False, ["Hold the top of a dip with locked arms and the shoulders pushed down away from the ears.", "Builds the shoulder stability and lockout strength dips need before you chase reps."]),
        ("Barbell Pullover", "\U0001F98B", "gym", False, ["Lying on a bench, lower a barbell back over your head with slightly bent arms, then pull it back over the chest.", "Stretches and loads the chest and lats; keep the ribs down."]),
        ("Machine Pullover", "\U0001F98B", "gym", False, ["A seated pullover machine that arcs the arms from overhead down to the torso.", "Constant tension on the lats with no balance demand; squeeze at the bottom and control the return."]),
        ("EZ-Bar Pullover", "\U0001F98B", "gym", False, ["A pullover with an EZ-bar, whose angled grips take strain off the wrists.", "Keep a soft elbow bend and move only at the shoulders."]),
        ("Cross-Bench Dumbbell Pullover", "\U0001F98B", "gym", False, ["A dumbbell pullover lying across a bench rather than along it, so the hips can drop for a deeper stretch.", "A classic ribcage and lat builder; go light and controlled."]),
        ("Incline Dumbbell Pullover", "\U0001F98B", "gym", False, ["A dumbbell pullover on a 30-45 degree incline bench.", "The angle keeps tension on the lats and chest right through the top of the arc."]),
        ("Single-Arm Cable Pullover", "\U0001F98B", "gym", True, ["A straight-arm cable pullover done one side at a time from a high pulley.", "Lets each lat work through its own full range; keep the torso still and the arm long."]),
        ("Kettlebell Pullover", "\U0001F514", "both", False, ["A floor or bench pullover holding a kettlebell by the horns.", "The offset weight makes the stretched position feel heavier; brace so the low back doesn't arch."]),
        ("Resistance Band Pullover", "\U0001F98B", "home", False, ["A pullover against a band anchored behind your head while lying on the floor.", "Band tension peaks at the top of the arc, making it a joint-friendly lat and chest option at home."]),
        ("Rope Cable Pullover", "\U0001F98B", "gym", False, ["A standing straight-arm pullover with a rope on a high pulley, pulling down and past the hips.", "Splitting the rope at the bottom gives a stronger lat squeeze."]),
    ],
    "Back": [
        ("Behind-the-Neck Lat Pulldown", "\U0001F9D7", "gym", False, ["A wide-grip pulldown taken to the base of the neck instead of the collarbone.", "Only worth doing if you have the shoulder mobility for it; keep the load light and the neck neutral."]),
        ("V-Bar Lat Pulldown", "\U0001F9D7", "gym", False, ["A pulldown using a narrow V-handle with the palms facing each other.", "The neutral grip lets you pull deeper into the lats with less elbow and shoulder strain."]),
        ("Half-Kneeling Single-Arm Lat Pulldown", "\U0001F9D7", "gym", True, ["A one-arm cable pulldown from a half-kneeling stance.", "The split position kills any body english so the lat does the pulling; keep the ribs stacked over the hips."]),
        ("Rope Lat Pulldown", "\U0001F9D7", "gym", False, ["A pulldown with a rope handle, splitting the hands apart as you pull past your chin.", "The extra range at the bottom gives a strong lat contraction."]),
        ("Lean-Back Lat Pulldown", "\U0001F9D7", "gym", False, ["A wide-grip pulldown with the torso leaned back around 30 degrees, pulling the bar to the upper chest.", "The angle turns it into more of a row so you can load the mid-back harder."]),
        ("Underhand Cable Pulldown", "\U0001F9D7", "gym", False, ["A shoulder-width pulldown with the palms facing you, driving the elbows down to your sides.", "Brings the biceps and lower lats in; keep the chest tall and don't swing."]),
        ("Archer Pull-Up", "\U0001F9D7", "both", True, ["A wide pull-up where you pull up and over toward one hand while the other arm stays straight.", "A stepping stone to the one-arm pull-up; alternate sides each rep."]),
        ("L-Sit Pull-Up", "\U0001F9D7", "both", False, ["A pull-up holding the legs straight out in front in an L shape throughout.", "Adds a brutal core hold to an already hard pull; don't let the legs drift down."]),
        ("Negative Pull-Up", "\U0001F9D7", "both", False, ["Jump or step to the top of a pull-up, then lower yourself over three to five seconds.", "The fastest route to a first unassisted rep; end the set once you can no longer control the descent."]),
        ("Chest-to-Bar Pull-Up", "\U0001F9D7", "both", False, ["A pull-up pulled high enough that the chest touches the bar.", "The extra range hammers the lats and mid-back; drive the elbows back and down at the top."]),
        ("Scapular Pull-Up", "\U0001F9D7", "both", False, ["Hanging with straight arms, pull the shoulder blades down and back to raise the body a few inches, then release.", "Teaches the scapular control every good pull-up starts with."]),
        ("Mixed-Grip Pull-Up", "\U0001F9D7", "both", False, ["A pull-up with one palm facing toward you and one away.", "Noticeably easier than a strict pull-up; swap grips set to set so you don't build a lopsided pattern."]),
        ("Tempo Pull-Up", "\U0001F9D7", "both", False, ["A pull-up done to a count -- two seconds up, one at the top, three down.", "Removing momentum makes light bodyweight sets brutally hard and builds real control."]),
        ("Fat-Grip Pull-Up", "\U0001F9D7", "both", False, ["A pull-up with thick grips, or a towel wrapped round the bar, to widen what you're holding.", "A serious grip and forearm builder on top of the usual back work."]),
        ("Close-Grip Chin-Up", "\U0001F9D7", "both", False, ["A chin-up with the hands only a few inches apart, palms facing you.", "The narrow grip pushes even more load onto the biceps; keep the elbows in front of the body."]),
        ("Negative Chin-Up", "\U0001F9D7", "both", False, ["Step to the top of a chin-up and lower over three to five seconds.", "The single best way to build toward a first full chin-up."]),
        ("Band-Assisted Chin-Up", "\U0001F9D7", "both", False, ["A chin-up with a resistance band under the knee or foot to offset some bodyweight.", "The band helps most at the bottom, exactly where the sticking point is."]),
        ("Assisted Chin-Up (Machine)", "\U0001F9D7", "gym", False, ["A chin-up on an assisted pull-up machine with a counterweighted knee pad.", "Dial the assistance down week to week until you can do it unassisted."]),
        ("L-Sit Chin-Up", "\U0001F9D7", "both", False, ["A chin-up holding the legs out straight in an L position.", "Combines a hard pull with a hard core hold; keep the legs level throughout."]),
        ("Isometric Chin-Up Hold", "\U0001F9D8", "both", False, ["Hold the top of a chin-up with the chin over the bar for as long as form holds.", "Builds the top-end strength that turns a grinding rep into a clean one."]),
        ("Ring Chin-Up", "\U0001F9D7", "both", False, ["A chin-up on gymnastic rings, letting the hands rotate naturally through the pull.", "The free rotation is much easier on the elbows than a fixed bar."]),
        ("Towel Chin-Up", "\U0001F9D7", "both", False, ["A chin-up gripping two towels draped over the bar.", "A savage grip and forearm builder; expect the grip to fail before the back does."]),
        ("Tempo Chin-Up", "\U0001F9D7", "both", False, ["A chin-up done to a strict count, typically three seconds down.", "Slowing the eccentric adds a lot of bicep and lat work at the same bodyweight."]),
        ("Smith Machine Shrug", "\U0001F3CB️", "gym", False, ["A shrug on a Smith machine, where the fixed bar path lets you focus purely on driving the traps up.", "Pause at the top and lower slowly; don't roll the shoulders."]),
        ("Machine Shrug", "\U0001F3CB️", "gym", False, ["A shrug on a dedicated shrug machine with padded handles.", "Constant tension and no grip limitation, so the traps take the whole set."]),
        ("Incline Dumbbell Shrug", "\U0001F3CB️", "gym", False, ["A shrug lying chest-down on an incline bench with dumbbells hanging.", "The angle shifts the work to the mid traps and rhomboids rather than the upper traps."]),
        ("Snatch-Grip Shrug", "\U0001F3CB️", "gym", False, ["A barbell shrug taken with a very wide, snatch-width grip.", "The wide hands bias the upper back and traps; keep the bar close to the body."]),
        ("Kettlebell Shrug", "\U0001F514", "both", False, ["A shrug holding a kettlebell in each hand at your sides.", "The lower centre of mass makes the grip work harder; drive the traps straight up, not back."]),
        ("Resistance Band Shrug", "\U0001F3CB️", "home", False, ["Stand on a band with a handle in each hand and shrug the shoulders straight up.", "Tension rises as you shrug, so squeeze hard at the top."]),
        ("Single-Arm Dumbbell Shrug", "\U0001F3CB️", "both", True, ["A shrug with one heavy dumbbell, the free hand steadying you on a rack.", "Lets you load one side properly and gives the core an anti-side-bend job."]),
        ("Prone Shrug (Chest-Supported)", "\U0001F3CB️", "gym", False, ["Face-down on an incline bench, shrug the shoulder blades together and up.", "Isolates the mid and lower traps with zero low-back involvement."]),
        ("Overhead Barbell Shrug", "\U0001F3CB️", "gym", False, ["Hold a barbell locked out overhead and shrug the shoulders up toward the ears.", "Builds the overhead-support strength that carries into pressing and the Olympic lifts."]),
        ("Banded Good Morning", "\U0001F9CD", "both", False, ["A good morning with a band looped behind the neck and under the feet.", "Tension peaks at lockout, so it hammers the glutes and hamstrings with no spinal loading."]),
        ("Dumbbell Good Morning", "\U0001F9CD", "both", False, ["A good morning holding a single dumbbell against the chest or on the upper back.", "A lighter, more accessible way to learn the hinge; keep the back flat and push the hips back."]),
        ("Safety Bar Good Morning", "\U0001F9CD", "gym", False, ["A good morning with a safety squat bar, whose handles and padding keep the shoulders comfortable.", "Lets you load the hinge heavier without shoulder strain."]),
        ("Single-Leg Good Morning", "\U0001F9CD", "both", True, ["A good morning balanced on one leg with the other extended behind.", "A hamstring and balance builder; go light and keep the hips square."]),
        ("Wide-Stance Good Morning", "\U0001F9CD", "gym", False, ["A barbell good morning with the feet set well outside shoulder width.", "The wide stance brings the adductors and glutes in alongside the hamstrings."]),
        ("Kneeling Face Pull", "\U0001F938", "gym", False, ["A cable face pull from a tall-kneeling position.", "Taking the legs out of it stops you leaning back and keeps the rear delts honest."]),
        ("Seated Face Pull", "\U0001F938", "gym", False, ["A face pull done seated at a cable station with the rope at head height.", "The fixed torso means every bit of the pull comes from the rear delts and mid-back."]),
        ("Single-Arm Face Pull", "\U0001F938", "gym", True, ["A one-armed cable face pull, pulling the handle toward the same-side ear.", "The extra rotation at the end gives the rear delt a stronger squeeze."]),
        ("High Cable Face Pull", "\U0001F938", "gym", False, ["A face pull with the pulley above head height, pulling down and back toward the forehead.", "Biases the lower traps as well as the rear delts."]),
        ("Low Cable Face Pull", "\U0001F938", "gym", False, ["A face pull from a low pulley, pulling up and back toward the face.", "The upward angle shifts the work toward the upper back; keep the elbows high."]),
        ("Prone Dumbbell Face Pull", "\U0001F938", "both", False, ["Face-down on an incline bench, pull two light dumbbells back toward your ears with the elbows high.", "A cable-free rear delt option; go light and pause at the top."]),
    ],
    "Shoulders": [
        ("Barbell Upright Row", "\U0001F3CB️", "gym", False, ["An upright row with a barbell pulled to chest height, elbows leading.", "Use a slightly wider grip and stop below the collarbone to keep the shoulders happy."]),
        ("Smith Machine Upright Row", "\U0001F3CB️", "gym", False, ["An upright row on a Smith machine, where the fixed path removes any swing.", "Lead with the elbows and stop the pull at chest height."]),
        ("Kettlebell Upright Row", "\U0001F514", "both", False, ["An upright row with one or two kettlebells hanging close to the body.", "The bells sit closer to your centre than dumbbells, which keeps the path tight."]),
        ("Resistance Band Upright Row", "\U0001F3CB️", "home", False, ["Stand on a band and row the handles up to chest height with high elbows.", "A joint-friendly way to train the traps and side delts at home."]),
        ("Single-Arm Cable Upright Row", "\U0001F3CB️", "gym", True, ["A one-armed upright row from a low pulley.", "The cable keeps tension through the whole pull and lets each side move naturally."]),
        ("Close-Grip Upright Row", "\U0001F3CB️", "gym", False, ["An upright row with the hands close together, biasing the traps over the delts.", "The narrow grip is harder on the shoulders -- keep the range short and the weight moderate."]),
        ("Snatch-Grip Upright Row", "\U0001F3CB️", "gym", False, ["A very wide-grip upright row, more of a high pull than a shrug.", "The width takes strain off the shoulder joint and hits the rear and side delts."]),
        ("Dumbbell Upright Row (Single-Arm)", "\U0001F3CB️", "both", True, ["An upright row with one dumbbell at a time, free hand on a bench for support.", "Lets you groove a cleaner path on each side; keep the elbow above the hand."]),
        ("Landmine Upright Row", "\U0001F3CB️", "gym", False, ["An upright row on the end of a landmine barbell, whose arc keeps the shoulders in a friendlier path.", "Pull the end of the bar to chest height and lower under control."]),
        ("Cable Rope Upright Row", "\U0001F3CB️", "gym", False, ["An upright row with a rope on a low pulley, letting the hands split as the elbows rise.", "The free hand position is much kinder to the wrists and shoulders."]),
    ],
    "Arms": [
        ("Rope Overhead Tricep Extension", "\U0001F4AA", "gym", False, ["Facing away from a low pulley with a rope overhead, extend the elbows until the arms lock out.", "The overhead position stretches the long head of the tricep hardest."]),
        ("Single-Arm Cable Tricep Extension", "\U0001F4AA", "gym", True, ["A one-armed cable extension, either overhead or down at your side.", "Lets you fix a weaker side and keeps constant tension through the whole range."]),
        ("Machine Tricep Extension", "\U0001F4AA", "gym", False, ["A seated tricep extension machine with the elbows fixed on a pad.", "No stabilising demand at all, so you can push the triceps close to failure safely."]),
        ("Incline Dumbbell Tricep Extension", "\U0001F4AA", "gym", False, ["A lying tricep extension on an incline bench, lowering the dumbbells past the head.", "The angle increases the stretch on the long head; keep the elbows pointed at the ceiling."]),
        ("Bodyweight Tricep Extension", "\U0001F4AA", "home", False, ["Set a bar or suspension straps at waist height and lower your forehead toward it by bending only at the elbows.", "A brutal bodyweight tricep builder; raise the bar to make it easier."]),
        ("Dumbbell Skull Crusher", "\U0001F4AA", "both", False, ["A lying tricep extension with a dumbbell in each hand, lowering to either side of the head.", "The independent hands are easier on the elbows than a fixed bar."]),
        ("Incline Skull Crusher", "\U0001F4AA", "gym", False, ["A skull crusher on an incline bench, which keeps tension on the triceps at lockout.", "Lower slowly toward the forehead and stop just short of full extension."]),
        ("Decline Skull Crusher", "\U0001F4AA", "gym", False, ["A skull crusher on a decline bench, lowering the bar behind the head.", "The decline keeps the triceps loaded through a longer range."]),
        ("Single-Arm Skull Crusher", "\U0001F4AA", "both", True, ["A one-armed lying tricep extension with a dumbbell.", "Great for evening out arms and for feeling the tricep work in isolation."]),
        ("Rope Skull Crusher", "\U0001F4AA", "gym", False, ["A lying skull crusher performed with a rope attached to a low pulley behind you.", "Constant cable tension makes the lockout the hardest part; split the rope at the top."]),
        ("Smith Machine Skull Crusher", "\U0001F4AA", "gym", False, ["A skull crusher on a Smith machine bar, whose fixed path removes any wobble.", "Ideal for pushing close to failure without a spotter."]),
        ("Single-Arm Cable Tricep Kickback", "\U0001F4AA", "gym", True, ["A kickback from a low pulley, hinged forward with the upper arm pinned to your side.", "Cable tension holds at lockout, where a dumbbell kickback gives up."]),
        ("Banded Tricep Kickback", "\U0001F4AA", "home", False, ["A kickback against a band anchored in front of you.", "Resistance rises as the arm straightens, so squeeze hard at lockout."]),
        ("Bent-Over Dumbbell Kickback (Both Arms)", "\U0001F4AA", "both", False, ["A tricep kickback with both arms at once, hinged forward at about 45 degrees.", "Keep the upper arms glued to your sides and move only at the elbows."]),
        ("Incline Dumbbell Bicep Curl", "\U0001F4AA", "gym", False, ["A curl seated back on an incline bench with the arms hanging behind the body.", "The stretched start position is one of the best long-head bicep builders."]),
        ("Preacher Bicep Curl", "\U0001F4AA", "gym", False, ["A curl with the upper arms resting on a preacher pad.", "The pad removes all swing so the biceps take the whole set; don't fully lock out at the bottom."]),
        ("Cable Bicep Curl", "\U0001F4AA", "gym", False, ["A standing curl on a low pulley with a straight or EZ attachment.", "Constant tension top to bottom, unlike a dumbbell that unloads at the top."]),
        ("Seated Dumbbell Bicep Curl", "\U0001F4AA", "both", False, ["A dumbbell curl performed seated upright on a bench.", "Sitting kills the hip drive people use to cheat standing curls."]),
        ("Reverse-Grip Bicep Curl", "\U0001F4AA", "both", False, ["A curl with the palms facing down throughout.", "Shifts the work to the brachialis and forearms; expect to use noticeably less weight."]),
        ("Cross-Body Bicep Curl", "\U0001F4AA", "both", True, ["A hammer-grip curl brought diagonally across the body toward the opposite shoulder.", "Hits the brachialis hard and builds arm thickness."]),
        ("Drag Bicep Curl", "\U0001F4AA", "both", False, ["A curl where the bar is dragged straight up the torso with the elbows travelling backward.", "Keeps tension on the biceps and takes the front delts out of it."]),
        ("Spider Bicep Curl", "\U0001F4AA", "gym", False, ["A curl lying chest-down on an incline bench with the arms hanging straight down.", "The arms-forward position makes the peak contraction the hardest part."]),
    ],
    "Legs": [
        ("Dumbbell Reverse Lunge", "\U0001F9B5", "both", True, ["A reverse lunge holding a dumbbell in each hand.", "Stepping back is easier on the knees than stepping forward; drive through the front heel to stand."]),
        ("Barbell Reverse Lunge", "\U0001F9B5", "gym", True, ["A reverse lunge with a barbell on the upper back.", "Lets you load the pattern heavily; keep the torso tall and the front shin vertical."]),
        ("Overhead Lunge", "\U0001F9B5", "gym", False, ["A walking or reverse lunge with a barbell or plate locked out overhead.", "The overhead load turns it into a full-body stability test; keep the ribs down and arms locked."]),
        ("Jumping Lunge", "\U0001F9B5", "home", False, ["From a split stance, jump and switch legs in the air, landing softly in a lunge.", "A quad and conditioning burner; land quietly and keep the front knee tracking over the toes."]),
        ("Deficit Forward Lunge", "\U0001F9B5", "both", False, ["A forward lunge stepping onto a low platform so the back knee travels below foot level.", "The extra range loads the glutes and hamstrings harder; control the descent."]),
        ("Landmine Reverse Lunge", "\U0001F9B5", "gym", True, ["A reverse lunge holding the end of a landmine barbell at the chest.", "The bar's arc helps you stay upright, making it a great heavy lunge for beginners."]),
        ("Slider Reverse Lunge", "\U0001F9B5", "home", True, ["A reverse lunge sliding the back foot along the floor on a towel or slider.", "The constant tension makes even bodyweight sets hard; move slowly in both directions."]),
        ("Calf Raise on Step", "\U0001F9B6", "both", False, ["A standing calf raise with the toes on a step so the heels can drop below the platform.", "The deeper stretch at the bottom is where most of the growth comes from."]),
        ("Barbell Calf Raise", "\U0001F9B6", "gym", False, ["A standing calf raise with a barbell on the upper back.", "Lets you load heavier than dumbbells allow; pause at the top of every rep."]),
        ("Hack Squat Calf Raise", "\U0001F9B6", "gym", False, ["A calf raise done standing on the footplate of a hack squat machine.", "The fixed back support means the calves take everything; press through the balls of the feet."]),
        ("Bent-Knee Calf Raise", "\U0001F9B6", "both", False, ["A calf raise with the knees softly bent throughout, biasing the soleus underneath the calf.", "Use higher reps -- the soleus responds to volume."]),
        ("Banded Calf Raise", "\U0001F9B6", "home", False, ["A calf raise standing on a band with the handles held at the shoulders.", "A simple loaded calf option at home; squeeze hard at the top."]),
        ("Narrow-Stance Leg Press", "\U0001F9B5", "gym", False, ["A leg press with the feet close together, low on the platform.", "Biases the quads and outer thigh; keep the knees tracking over the toes."]),
        ("Wide-Stance Leg Press", "\U0001F9B5", "gym", False, ["A leg press with the feet set wide and toes turned slightly out.", "Brings the adductors and glutes in alongside the quads."]),
        ("High-Foot Leg Press", "\U0001F9B5", "gym", False, ["A leg press with the feet high on the platform.", "Shifts the load toward the glutes and hamstrings; don't let the low back round at the bottom."]),
        ("Low-Foot Leg Press", "\U0001F9B5", "gym", False, ["A leg press with the feet low on the platform.", "A pure quad emphasis; keep the heels down and stop short of lockout."]),
        ("Horizontal Leg Press", "\U0001F9B5", "gym", False, ["A seated leg press where you push the platform straight out in front of you.", "Easier on the low back than the 45-degree sled; control the return."]),
        ("Vertical Leg Press", "\U0001F9B5", "gym", False, ["A leg press pushing the platform straight up while lying flat on your back.", "Very demanding on the hips and low back -- keep the range moderate and the weight sensible."]),
        ("Paused Leg Press", "\U0001F9B5", "gym", False, ["A leg press held for two seconds at the bottom before pressing back up.", "The pause removes the bounce and builds strength out of the deep position."]),
        ("Feet-Together Leg Press", "\U0001F9B5", "gym", False, ["A leg press with the feet touching in the middle of the platform.", "Hits the outer quad sweep; keep the knees from caving in."]),
        ("Banded Leg Press", "\U0001F9B5", "gym", False, ["A leg press with bands added to the sled for accommodating resistance.", "Resistance rises as you extend, so the lockout is the hardest part."]),
        ("Dumbbell Step-Up", "\U0001F9B5", "both", True, ["A step-up onto a box holding a dumbbell in each hand.", "Drive through the whole front foot and avoid pushing off the back leg."]),
        ("Barbell Step-Up", "\U0001F9B5", "gym", True, ["A step-up with a barbell on the upper back.", "Heavy and demanding on balance; start with a low box and keep the torso tall."]),
        ("Lateral Step-Up", "\U0001F9B5", "both", True, ["A step-up done sideways onto the box, leading with the outside leg.", "Trains the glute medius and knee stability in a plane most training ignores."]),
        ("High Box Step-Up", "\U0001F9B5", "both", True, ["A step-up onto a box at or above knee height.", "The deep start position loads the glutes hard; go slow and don't push off the trailing foot."]),
        ("Kettlebell Step-Up", "\U0001F514", "both", True, ["A step-up with a kettlebell held in the rack position at the shoulder.", "The front-loaded position makes the core work to keep you upright."]),
        ("Step-Up with Knee Drive", "\U0001F9B5", "both", True, ["A step-up finished by driving the trailing knee up to hip height.", "Adds a balance and hip-flexor challenge; pause at the top of each rep."]),
        ("Slow-Tempo Step-Up", "\U0001F9B5", "both", True, ["A step-up taking three seconds up and three seconds down.", "The slow eccentric is where the quad and glute growth is; no bouncing off the floor."]),
        ("Crossover Step-Up", "\U0001F9B5", "both", True, ["Standing beside a box, cross the far leg over and step up onto it.", "A strong glute medius builder; keep the hips level throughout."]),
        ("Bench Step-Up", "\U0001F9B5", "both", True, ["A step-up onto a flat bench, the most common gym platform for the movement.", "Check the bench is stable, and step down under control rather than dropping."]),
        ("Banded Step-Up", "\U0001F9B5", "home", True, ["A step-up standing on a band with the handles held at the shoulders.", "Resistance increases as you extend the hip, so the top of the rep is hardest."]),
        ("Deficit Step-Down", "\U0001F9B5", "both", True, ["Standing on a box, lower one foot slowly to tap the floor and press back up.", "An eccentric-focused single-leg builder that's excellent for knee health."]),
        ("Smith Machine Hip Thrust", "\U0001F351", "gym", False, ["A hip thrust with the bar on a Smith machine, so the path is fixed and setup is quick.", "Drive through the heels and squeeze the glutes hard at the top."]),
        ("Banded Hip Thrust", "\U0001F351", "home", False, ["A hip thrust with a band over the hips or around the knees.", "Tension peaks at lockout, exactly where the glutes work hardest."]),
        ("Feet-Elevated Hip Thrust", "\U0001F351", "gym", False, ["A hip thrust with the feet raised on a low box or plates.", "The longer range shifts more work to the hamstrings alongside the glutes."]),
        ("Paused Hip Thrust", "\U0001F351", "gym", False, ["A hip thrust held for two to three seconds at full lockout each rep.", "The pause forces a real glute contraction instead of a bounce."]),
        ("Bodyweight Hip Thrust", "\U0001F351", "home", False, ["A shoulders-on-bench hip thrust with no external load.", "A great way to learn the pattern and to warm the glutes up before heavy work."]),
        ("Kettlebell Hip Thrust", "\U0001F514", "both", False, ["A hip thrust with a kettlebell resting across the hips.", "Easier to set up solo than a barbell; keep the chin tucked and ribs down."]),
        ("Cable Hip Thrust", "\U0001F351", "gym", False, ["A hip thrust driven against a low cable attached at the hips.", "The cable's constant tension makes lockout the hardest point of every rep."]),
        ("Barbell Glute Bridge", "\U0001F351", "gym", False, ["A glute bridge from the floor with a barbell across the hips.", "Shorter range than a hip thrust but easy to load heavy; squeeze at the top."]),
        ("Dumbbell Glute Bridge", "\U0001F351", "both", False, ["A floor glute bridge with a dumbbell held across the hips.", "A simple loaded glute option that needs no bench."]),
        ("Feet-Elevated Glute Bridge", "\U0001F351", "home", False, ["A glute bridge with the heels up on a step or bench.", "Increases the hamstring share of the work; keep the ribs down."]),
        ("Glute Bridge March", "\U0001F351", "home", False, ["Hold the top of a glute bridge and lift one knee at a time toward your chest.", "The single-leg support turns it into an anti-rotation core drill too."]),
        ("Frog Glute Bridge", "\U0001F351", "home", False, ["A glute bridge with the soles of the feet together and knees splayed out.", "The externally rotated hips bias the upper glutes; squeeze hard for a full second."]),
        ("Banded Glute Kickback", "\U0001F351", "home", True, ["A kneeling or standing kickback against a band looped round the ankle.", "Drive the heel straight back and stop when the low back wants to arch."]),
        ("Quadruped Glute Kickback", "\U0001F351", "home", True, ["On hands and knees, press one heel toward the ceiling with the knee bent at 90 degrees.", "Keep the hips square and the movement small and controlled."]),
        ("Sliding Hamstring Curl", "\U0001F9B5", "home", False, ["Lying on your back with the heels on sliders, bridge up and pull the heels toward the hips.", "A punishing bodyweight hamstring curl; keep the hips high throughout."]),
        ("Banded Hamstring Curl", "\U0001F9B5", "home", True, ["A lying leg curl against a band anchored behind you.", "A joint-friendly way to train the hamstrings without a machine."]),
        ("Single-Leg Stability Ball Hamstring Curl", "\U0001F3D0", "both", True, ["A stability ball hamstring curl done one leg at a time.", "Roughly doubles the load per leg and adds a serious stability demand."]),
        ("Razor Hamstring Curl", "\U0001F9B5", "both", False, ["A kneeling hamstring curl with the hips flexing back and then extending as you lower and rise.", "A slightly more forgiving progression toward the Nordic curl."]),
        ("Standing Hamstring Curl (Machine)", "\U0001F9B5", "gym", True, ["A one-leg-at-a-time curl on a standing leg-curl machine.", "Lets each hamstring work independently; keep the hips pressed into the pad."]),
        ("Eccentric Nordic Hamstring Curl", "\U0001F9B5", "both", False, ["A Nordic curl lowering as slowly as possible, then pushing back up with the hands.", "The gold-standard hamstring injury-prevention exercise; three to five reps is plenty."]),
        ("Banded Hip Abduction", "\U0001F351", "home", False, ["Seated or standing with a band above the knees, press the knees apart against the band.", "A simple glute medius burner; hold each rep for a beat."]),
        ("Side-Lying Hip Abduction", "\U0001F351", "home", True, ["Lying on your side, raise the top leg toward the ceiling with the toes pointing forward.", "Keep the hips stacked so the glute does the work, not the hip flexor."]),
        ("Standing Cable Hip Abduction", "\U0001F351", "gym", True, ["With a cuff on the ankle, sweep the leg out to the side against a low cable.", "Trains the glute medius standing, the way it actually works when you walk."]),
        ("Banded Hip Adduction", "\U0001F9B5", "home", True, ["With a band anchored to the side and looped round the ankle, pull the leg in across the body.", "Strengthens the inner thigh, which most programs never train directly."]),
        ("Side-Lying Hip Adduction", "\U0001F9B5", "home", True, ["Lying on your side with the top leg crossed in front, raise the bottom leg off the floor.", "A simple bodyweight adductor exercise; move slowly and keep the leg straight."]),
        ("Copenhagen Adduction", "\U0001F9B5", "both", True, ["A side plank with the top leg on a bench, lifting the bottom leg up to meet it.", "One of the strongest groin-injury-prevention exercises there is; start with the knee on the bench."]),
        ("Standing Hip Adduction (Machine)", "\U0001F9B5", "gym", True, ["A standing adduction machine, sweeping one leg in across the body.", "Keep the torso upright and control the return; don't let the leg snap back."]),
    ],
    "Core": [
        ("Machine Crunch", "\U0001F300", "gym", False, ["A seated ab crunch machine with the chest pad loaded by a weight stack.", "The easiest way to progressively overload the abs; curl the ribs toward the hips."]),
        ("Decline Crunch", "\U0001F300", "gym", False, ["A crunch on a decline bench with the feet anchored.", "The angle adds resistance at the top of the crunch; don't pull on your neck."]),
        ("Stability Ball Crunch", "\U0001F3D0", "both", False, ["A crunch lying back over a stability ball so the spine can extend past flat.", "The extra range makes it far more effective than a floor crunch."]),
        ("Oblique Crunch", "\U0001F300", "home", True, ["A crunch driving the elbow toward the opposite knee, or crunching sideways with the knees dropped.", "Hits the obliques; hold the top for a beat each rep."]),
        ("Frog Crunch", "\U0001F300", "home", False, ["A crunch with the soles of the feet together and knees splayed out.", "Takes the hip flexors out of the movement so the abs do everything."]),
        ("Butterfly Crunch", "\U0001F300", "home", False, ["A crunch with the legs in a butterfly position and arms reaching overhead.", "The long lever makes a bodyweight crunch genuinely hard."]),
        ("Long-Arm Crunch", "\U0001F300", "home", False, ["A crunch with the arms held straight overhead beside the ears throughout.", "The extended arms lengthen the lever and increase the ab demand."]),
        ("Double Crunch", "\U0001F300", "home", False, ["Crunch the shoulders and the knees toward each other at the same time.", "Trains the upper and lower abs in one movement; exhale hard at the top."]),
        ("Weighted Sit-Up", "\U0001F300", "both", False, ["A sit-up holding a plate or dumbbell against the chest.", "The simplest way to make sit-ups a strength exercise rather than an endurance one."]),
        ("Butterfly Sit-Up", "\U0001F300", "home", False, ["A sit-up with the soles of the feet together and knees out.", "The open hips stop the hip flexors taking over; reach past the feet at the top."]),
        ("V Sit-Up", "\U0001F300", "home", False, ["From lying flat, lift the legs and torso together to meet in a V shape.", "Hits the whole front of the core; lower both halves slowly."]),
        ("Stability Ball Sit-Up", "\U0001F3D0", "both", False, ["A full sit-up performed lying back over a stability ball.", "The extended range makes it a much fuller ab contraction than a floor sit-up."]),
        ("Twisting Sit-Up", "\U0001F300", "home", False, ["A sit-up rotating toward one knee at the top, alternating sides.", "Brings the obliques into a standard sit-up."]),
        ("Anchored Sit-Up", "\U0001F300", "both", False, ["A sit-up with the feet hooked under a bar or held down.", "Lets you sit up against heavier loads, at the cost of more hip flexor involvement."]),
        ("Medicine Ball Sit-Up Throw", "\U0001F3D0", "both", False, ["Sit up and throw a medicine ball to a partner or wall at the top of each rep.", "Adds explosive power to the pattern; catch it and lower under control."]),
        ("Hanging Straight-Leg Raise", "\U0001F300", "both", False, ["A hanging leg raise with the knees locked straight throughout.", "Far harder than the bent-knee version; stop swinging before starting the next rep."]),
        ("Weighted Hanging Leg Raise", "\U0001F300", "gym", False, ["A hanging leg raise with a dumbbell held between the feet.", "The most direct way to overload the lower abs; keep the movement strict."]),
        ("Parallel Bar Leg Raise", "\U0001F300", "gym", False, ["A leg raise supported on parallel bars or a captain's chair with the elbows down.", "Removes the grip limitation so the abs are the only thing that fails."]),
        ("Incline Bench Leg Raise", "\U0001F300", "gym", False, ["A leg raise lying on a decline bench gripping the top for support.", "The angle keeps the abs loaded even at the bottom of each rep."]),
        ("Roman Chair Leg Raise", "\U0001F300", "gym", False, ["A leg raise from a Roman chair with the back supported.", "A stable position that lets you focus purely on curling the pelvis up."]),
        ("Side-Lying Leg Raise", "\U0001F300", "home", True, ["Lying on your side, raise both legs together off the floor.", "A tough oblique and hip exercise; keep the shoulders stacked."]),
        ("Banded Leg Raise", "\U0001F300", "home", False, ["A lying leg raise against a band anchored behind your head and looped round the feet.", "Adds resistance to a bodyweight staple; lower slowly against the band."]),
        ("Bench Leg Raise", "\U0001F300", "both", False, ["A lying leg raise on a flat bench, gripping the bench behind your head with the hips just off the edge.", "The extra range below the bench loads the lower abs harder than the floor."]),
        ("Plank Jack", "\U0001F9D8", "home", False, ["In a plank, jump the feet wide and back together while keeping the hips still.", "Adds a conditioning element to a core hold; don't let the hips bounce."]),
        ("Plank to Push-Up", "\U0001F9D8", "home", False, ["Move from a forearm plank up to a high plank one arm at a time, then back down.", "An anti-rotation core exercise with a tricep and shoulder bonus."]),
        ("Reverse Plank", "\U0001F9D8", "home", False, ["Sit with the legs straight and hands behind you, then lift the hips into a straight line facing up.", "Trains the posterior chain and counteracts a day of sitting."]),
        ("Plank with Leg Lift", "\U0001F9D8", "home", False, ["A forearm plank raising one leg a few inches off the floor at a time.", "Taking away a base of support forces the deep core to fight rotation."]),
        ("Single-Arm Plank", "\U0001F9D8", "home", True, ["A plank holding one arm off the floor, extended or tucked behind the back.", "A serious anti-rotation challenge; keep the hips completely level."]),
        ("Plank Reach-Out", "\U0001F9D8", "home", True, ["From a forearm plank, reach one arm straight out in front and hold before swapping.", "The long lever makes the abs work far harder than a standard plank."]),
        ("Cable Torso Twist", "\U0001FA93", "gym", True, ["Standing side-on to a cable at chest height, rotate the handle across the body with straight arms.", "A pure rotational obliques exercise; turn from the ribcage, not the arms."]),
        ("Standing Band Twist", "\U0001FA93", "home", True, ["The same rotation against a band anchored at chest height.", "Keep the hips facing forward so the rotation comes from the trunk."]),
        ("Plank Hip Twist", "\U0001FA93", "home", False, ["In a forearm plank, rotate the hips to tap each side toward the floor.", "Trains the obliques dynamically; move slowly and keep the shoulders square."]),
        ("Hanging Knee Twist", "\U0001FA93", "both", False, ["Hanging from a bar, raise the knees and rotate them to one side, alternating.", "Combines a lower-ab raise with an oblique twist; control the swing."]),
        ("Weighted Russian Twist", "\U0001FA93", "both", False, ["A Russian twist holding a plate or dumbbell, rotating hip to hip.", "Keep the chest tall and the feet up; rotate the ribcage rather than swinging the arms."]),
        ("Seated Barbell Twist", "\U0001FA93", "gym", False, ["Seated on a bench with a light bar across the shoulders, rotate side to side.", "A classic oblique warm-up; keep it light and never force the range."]),
        ("Half-Kneeling Cable Rotation", "\U0001FA93", "gym", True, ["A cable rotation from a half-kneeling stance, turning away from the machine.", "The locked-down hips mean all the rotation comes from the trunk."]),
        ("Standing Cable Rotation", "\U0001FA93", "gym", True, ["A standing cable rotation at chest height, pivoting the back foot as you turn.", "The closest gym exercise to the rotation used in throwing and swinging sports."]),
    ],
    "Full Body / Conditioning": [
        ("American Kettlebell Swing", "\U0001F514", "both", False, ["A kettlebell swing driven all the way overhead rather than to chest height.", "More shoulder demand; only add the overhead finish once your hinge is solid."]),
        ("Single-Arm Kettlebell Swing", "\U0001F514", "both", True, ["A kettlebell swing with one hand, switching hands at the top or between sets.", "Adds a strong anti-rotation core demand; keep the shoulder packed."]),
        ("Double Kettlebell Swing", "\U0001F514", "gym", False, ["A swing with a kettlebell in each hand, feet set slightly wider.", "Roughly doubles the load, so keep the reps crisp and the back flat."]),
        ("Dumbbell Swing", "\U0001F3CB️", "both", False, ["A hip-hinge swing holding one dumbbell vertically by the head.", "The obvious swing substitute when there's no kettlebell; snap the hips and let the arms be ropes."]),
        ("Banded Kettlebell Swing", "\U0001F514", "gym", False, ["A swing with a band running from the bell to the floor for extra resistance at the top.", "Forces a sharper hip snap; keep the reps low and explosive."]),
        ("Lateral Box Jump", "\U0001F3C3", "both", False, ["A box jump taking off and landing sideways onto the box.", "Builds lateral power most jumping never touches; land softly with the knees tracking out."]),
        ("Single-Leg Box Jump", "\U0001F3C3", "both", True, ["A box jump taking off from one leg onto a low box.", "Demanding on the ankle and knee -- start very low and step down between reps."]),
        ("Vertical Jump", "\U0001F3C3", "both", False, ["A maximal two-foot jump straight up, reaching for a target.", "The simplest measure of lower-body power; take full rest between reps."]),
        ("Hurdle Jump", "\U0001F3C3", "gym", False, ["Consecutive two-foot jumps over a line of low hurdles.", "Trains fast, stiff ground contacts; keep the ground time short."]),
        ("Split Jump", "\U0001F3C3", "home", False, ["From a lunge, jump straight up and land in the same stance without switching legs.", "A single-leg power builder; keep the front knee stable on landing."]),
        ("Countermovement Jump", "\U0001F3C3", "both", False, ["A vertical jump with a fast dip before takeoff.", "Trains the stretch-shortening cycle; go for maximum height on every rep."]),
        ("Seated Box Jump", "\U0001F3C3", "gym", False, ["A box jump starting seated on a bench, so there's no countermovement to help you.", "Pure concentric power; stand fully at the top of each rep."]),
        ("Depth Drop", "\U0001F3C3", "gym", False, ["Step off a low box and land in an athletic position, absorbing the landing softly.", "Teaches the landing mechanics that make jump training safe; master this before depth jumps."]),
    ],
}


def _build():
    out = []
    for category, items in _BY_CATEGORY.items():
        for name, emoji, location, unilateral, description in items:
            out.append({
                "name": name,
                "category": category,
                "emoji": emoji,
                "location": location,
                "unilateral": unilateral,
                "description": description,
            })
    return out


VARIATION_EXERCISES = _build()
