"""~300 additional muscle-building exercises, kept in their own module so
the big data block stays out of workout_library.py / exercise_details.py
and both files can merge it in from a single source of truth.

Each entry carries everything the two catalog files need:
    name        -- the exact display/log string (never collides with an
                   existing WORKOUT_EXERCISES name)
    category    -- one of the existing EXERCISE_CATEGORIES keys
    emoji       -- REUSED from the palette already present in
                   exercise_details.py (same movement -> same emoji as its
                   existing siblings: presses -> 🏋️, flyes/rear-delt -> 🦋,
                   rows -> 🚣, vertical pulls -> 🧗, side/front raises -> 🤸,
                   curls/tricep isolation -> 💪, squats -> 🦵, glutes -> 🍑,
                   calves -> 🦶, crunches/twists -> 🌀, planks/holds -> 🧘,
                   ...). If no existing emoji genuinely fits a movement it is
                   left blank ("") on purpose, per the "leave it out and make
                   it blank" instruction, rather than forcing a mismatch.
    location    -- "gym" / "home" / "both", same meaning as EXERCISE_LOCATIONS
    unilateral  -- True if it's commonly done one side at a time with an
                   independently-loadable implement (dumbbell / cable /
                   kettlebell / band / single limb); feeds UNILATERAL_EXERCISES
    description -- one-line how-to, same voice as the existing details

This module imports nothing from the rest of the app, so it can't create an
import cycle with the files that consume it.
"""

# (name, emoji, location, unilateral, description)
_BY_CATEGORY = {
    "Chest": [
        ("Smith Machine Bench Press", "🏋️", "gym", False, "Press the fixed bar straight up and down on a Smith machine — the guided track lets you push closer to failure without a spotter, so control the descent to your mid-chest and don't bounce."),
        ("Smith Machine Incline Press", "🏋️", "gym", False, "Same guided press on a 30–45° incline bench — lower to your upper chest and drive up, letting the fixed track take the balancing work so you can focus on the squeeze."),
        ("Machine Chest Press", "🏋️", "gym", False, "Sit with the handles at mid-chest height and press straight out until your arms are nearly locked, then return under control — a beginner-friendly way to overload the chest with no balance demand."),
        ("Incline Machine Chest Press", "🏋️", "gym", False, "A seated machine press angled to bias the upper chest — press up and slightly in, and stop just short of lockout to keep constant tension on the pecs."),
        ("Hammer Strength Chest Press", "🏋️", "gym", False, "A plate-loaded converging press where the handles arc toward each other at the top for a stronger peak contraction — press evenly with both arms and control the stretch."),
        ("Wide-Grip Bench Press", "🏋️", "gym", False, "A barbell bench with a grip wider than shoulder width to bias the chest over the triceps — shorten the range slightly and keep your shoulder blades pinned to protect the shoulders."),
        ("Reverse-Grip Bench Press", "🏋️", "gym", False, "Bench with an underhand (supinated) grip to shift load onto the upper chest — use a spotter, keep the wrists stacked, and start lighter since the grip feels unfamiliar."),
        ("Spoto Press", "🏋️", "gym", False, "A bench press paused an inch off the chest rather than touching — the mid-air hold kills momentum and builds pressing strength off the bottom; hold for a beat, then drive up."),
        ("Board Press", "🏋️", "gym", False, "A partial bench press to a board (or foam block) on the chest, training lockout strength through a shortened range — press explosively off the board without bouncing."),
        ("Pin Press", "🏋️", "gym", False, "A bench press starting from dead-stop on the rack's safety pins, removing the stretch reflex — press from a full stop to build raw power out of the bottom position."),
        ("Neutral-Grip Dumbbell Press", "🏋️", "both", False, "Press two dumbbells with palms facing each other — the neutral grip is easier on the shoulders and hits the inner chest and triceps hard; keep the dumbbells stacked over the elbows."),
        ("Dumbbell Squeeze Press", "🏋️", "both", False, "Press two dumbbells while actively pushing them together the whole rep — the constant inward pressure maximizes chest activation; use a lighter load and feel the pecs squeeze at the top."),
        ("Svend Press", "🏋️", "both", False, "Press a single weight plate (or two pressed together) straight out from your chest with both palms, crushing it inward the whole time — a pure inner-chest contraction move with light load."),
        ("Incline Dumbbell Fly", "🦋", "both", False, "On an incline bench, open two dumbbells in a wide arc with a slight elbow bend, feeling the upper-chest stretch, then hug them back together — keep the elbows soft and never lock them."),
        ("Decline Dumbbell Fly", "🦋", "both", False, "On a decline bench, arc two dumbbells out and back with a soft elbow bend to bias the lower chest — control the stretch and squeeze the pecs at the top."),
        ("Flat Dumbbell Fly", "🦋", "both", False, "Lying flat, open two dumbbells in a wide arc with slightly bent elbows until you feel a chest stretch, then bring them together over your chest — think 'hugging a barrel,' not pressing."),
        ("Incline Cable Fly", "🦋", "gym", False, "Set the cables low and fly upward and inward on an incline bench (or standing) to load the upper chest with constant tension — squeeze the pecs together at the top of each rep."),
        ("Low-to-High Cable Fly", "🦋", "gym", False, "From low pulleys, sweep both handles up and together toward eye level, biasing the upper chest — keep a soft elbow bend and finish with the hands crossing or touching."),
        ("High-to-Low Cable Fly", "🦋", "gym", False, "From high pulleys, sweep both handles down and together toward your hips to bias the lower chest — squeeze at the bottom and resist the stretch on the way back up."),
        ("Single-Arm Cable Fly", "🦋", "gym", True, "A one-arm cable fly across the body — the single-side setup lets each pec work through a fuller range and evens out strength differences; control the stretch behind you."),
        ("Resistance Band Fly", "🦋", "home", False, "Anchor a band behind you and fly both handles together in front of your chest — the band's tension peaks at full contraction, so pause and squeeze the pecs at the finish."),
        ("Machine Fly", "🦋", "gym", False, "Seated pec-deck-style fly with arms on the pads or handles — bring the arms together in a smooth arc and squeeze, keeping the shoulders down and back throughout."),
        ("Dumbbell Pullover", "🏋️", "both", False, "Lying across or along a bench, lower one dumbbell in an arc behind your head with slightly bent arms, feeling the chest and lat stretch, then pull it back over your chest."),
        ("Cable Pullover", "🏋️", "gym", False, "Standing at a high pulley with a rope or bar, keep your arms long and pull the handle down in an arc to your thighs — a constant-tension pullover for the chest and lats."),
        ("Wide-Grip Push-Up", "🤸", "home", False, "A push-up with hands well outside shoulder width to emphasize the chest — keep a straight line from head to heels and lower until your chest nearly touches the floor."),
        ("Close-Grip Push-Up", "🤸", "home", False, "A push-up with hands close together under your chest to shift load onto the triceps and inner chest — keep the elbows tucked toward your sides as you lower."),
        ("Archer Push-Up", "🤸", "home", True, "A push-up shifting your weight over one arm while the other stays straight out to the side — a bodyweight step toward the one-arm push-up; alternate sides each rep."),
        ("Deficit Push-Up", "🤸", "home", False, "A push-up with hands raised on blocks or plates so your chest sinks below hand level — the extra range deepens the chest stretch; control the bottom and don't sag your hips."),
        ("Weighted Push-Up", "🤸", "home", False, "A standard push-up with a plate or weighted vest on your back to add resistance once bodyweight reps get easy — keep the core braced so the load doesn't sink your hips."),
        ("Ring Push-Up", "🤸", "both", False, "A push-up on gymnastic rings — the unstable handles force the chest and stabilizers to work overtime; keep the rings from flaring and turn the palms out at the top to squeeze."),
        ("Clap Push-Up", "🤸", "home", False, "An explosive push-up where you push hard enough to leave the floor and clap before landing softly — a power move for the chest; reset your line before each rep."),
        ("Feet-Elevated Push-Up", "🤸", "home", False, "A push-up with your feet raised on a bench or box to shift more load to the upper chest and shoulders — keep a rigid plank line and lower with control."),
        ("Weighted Chest Dip", "🤾", "both", False, "A chest dip with a belt or dumbbell for added load — lean your torso forward and let the elbows flare slightly to bias the chest; lower until you feel the stretch, then press up."),
        ("Ring Dip", "🤾", "both", False, "A dip on rings, adding a big stability demand over parallel bars — keep the rings tight to your body, lean forward for chest, and press to a strong lockout with the palms turned out."),
        ("Machine-Assisted Dip", "🤾", "gym", False, "A dip on an assisted machine that supports part of your weight via a knee pad — lets you build to full bodyweight dips with clean depth and a forward chest lean."),
        ("Standing Cable Chest Press", "🏋️", "gym", False, "From chest-height pulleys, press both handles forward and together while standing — the core braces against the load, making it a chest press plus anti-rotation trainer."),
        ("Single-Arm Machine Chest Press", "🏋️", "gym", True, "A one-arm chest press on a machine — pressing one side at a time adds an anti-rotation core demand and lets you even out left/right strength; control the return."),
        ("Guillotine Press", "🏋️", "gym", False, "A wide-grip bench press lowered toward the neck/upper chest with elbows flared to maximize chest stretch — a shoulder-demanding variation, so go light and use a spotter."),
        ("Larsen Press", "🏋️", "gym", False, "A bench press with your legs held straight out (no leg drive or foot contact) — it removes the arch and forces the chest and shoulders to do all the work; keep it strict and lighter."),
        ("Incline Cable Press", "🏋️", "gym", False, "An incline press using cables instead of a bar, giving smooth constant tension up the whole range — press up and slightly together, and stop short of lockout to keep the pecs loaded."),
        ("Plate Pinch Press", "🏋️", "both", False, "Press a weight plate held between flat palms out and back from your chest, crushing it the entire time — combines an inner-chest squeeze with a grip challenge; keep it light and slow."),
        ("Banded Push-Up", "🤸", "home", False, "A push-up with a resistance band looped across your upper back and held under both hands — the band adds tension that peaks at lockout, overloading the top of the press."),
        ("Incline Dumbbell Squeeze Press", "🏋️", "both", False, "An incline dumbbell press keeping the weights pressed together the whole rep — the constant inward pressure lights up the upper and inner chest; go lighter and squeeze at the top."),
    ],
    "Back": [
        ("Neutral-Grip Lat Pulldown", "🧗", "gym", False, "A lat pulldown using a neutral (palms-facing) V-handle — easier on the shoulders and biceps-friendly; pull the handle to your upper chest and drive the elbows down and back."),
        ("Reverse-Grip Lat Pulldown", "🧗", "gym", False, "A pulldown with a shoulder-width underhand grip to bias the lower lats and hit the biceps more — pull the bar to your chest, leading with the elbows, and squeeze at the bottom."),
        ("Single-Arm Lat Pulldown", "🧗", "gym", True, "A one-arm cable pulldown that lets each lat move through a fuller range and evens out imbalances — pull the handle down and slightly back, rotating the torso for extra stretch."),
        ("Machine Lat Pulldown", "🧗", "gym", False, "A plate-loaded or selectorized pulldown machine with a chest pad — the fixed path lets you focus purely on driving the elbows down to your sides and squeezing the lats."),
        ("Kneeling Cable Pulldown", "🧗", "gym", False, "Kneel facing a high pulley and pull a rope or bar down to your collarbone — the kneeling position removes leg drive and isolates the lats through a strict vertical pull."),
        ("Wide-Grip Pull-Up", "🧗", "both", False, "A pull-up with hands well outside shoulder width to emphasize the lats and upper back — pull your chest toward the bar and avoid swinging; add weight once strict reps are easy."),
        ("Neutral-Grip Pull-Up", "🧗", "both", False, "A pull-up on parallel (palms-facing) handles — the most shoulder-friendly grip, blending lat and mid-back work; pull to chest height and control the descent."),
        ("Commando Pull-Up", "🧗", "both", False, "A pull-up gripping the bar lengthwise with hands together, pulling your head to one side then the other — hits the lats and arms with an added rotational challenge."),
        ("Weighted Pull-Up", "🧗", "both", False, "A strict pull-up with a dip belt or dumbbell between the feet for added load — keep every rep full-range from a dead hang to chin over the bar; ideal for building back strength."),
        ("Weighted Chin-Up", "🧗", "both", False, "An underhand-grip chin-up loaded with a belt or dumbbell — the supinated grip drives heavy biceps and lat involvement; pull from a full hang to chest and lower under control."),
        ("Assisted Pull-Up (Machine)", "🧗", "gym", False, "A pull-up on a machine that offsets part of your bodyweight with a knee or foot platform — lets you build strict, full-range pulling strength toward an unassisted pull-up."),
        ("Band-Assisted Pull-Up", "🧗", "both", False, "A pull-up with a resistance band looped under your feet or knee for a boost out of the bottom — the assistance fades near the top, so still finish with chin over the bar."),
        ("Pendlay Row", "🚣", "gym", False, "A barbell row where each rep starts from a dead stop on the floor with a flat back and explosive pull to the lower chest — builds a powerful, strict mid-back off the ground."),
        ("Yates Row", "🚣", "gym", False, "A barbell row with an underhand grip and a more upright ~45° torso, pulling to the waist — the angle lets you handle heavier loads and biases the lower lats and upper back."),
        ("Reverse-Grip Barbell Row", "🚣", "gym", False, "A bent-over barbell row with an underhand grip — draws the elbows tighter to the body to emphasize the lower lats and biceps; keep the back flat and pull to the belly button."),
        ("Chest-Supported Row", "🚣", "gym", False, "A row with your chest braced on an incline bench or machine pad — the support removes lower-back strain and cheating, isolating the mid-back; squeeze the shoulder blades at the top."),
        ("Chest-Supported Dumbbell Row", "🚣", "both", False, "Lie face-down on an incline bench and row two dumbbells up to your ribs — the chest support forces strict form so the lats and rhomboids do all the pulling."),
        ("Incline Dumbbell Row", "🚣", "both", False, "Chest propped on an incline bench, row two dumbbells up and back with the elbows flaring slightly to hit the upper back and rear delts — pause and squeeze at the top."),
        ("Meadows Row", "🚣", "gym", True, "A one-arm row on the end of a landmine barbell, gripping the sleeve — the angle gives a deep lat stretch and strong contraction; brace the free hand on your knee and row to the hip."),
        ("Landmine Row", "🚣", "gym", False, "Straddle a landmine barbell and row the loaded end to your chest with both hands or a handle — the arc keeps constant tension on the mid-back; keep the hips hinged and back flat."),
        ("Machine Row", "🚣", "gym", False, "A seated plate-loaded or selectorized row with a chest pad — pull the handles to your torso, driving the elbows back and squeezing the shoulder blades; a strict, back-only pull."),
        ("Hammer Strength Row", "🚣", "gym", False, "A plate-loaded chest-supported row with independent handles — the converging path gives a strong peak contraction; row each side evenly and pause at the squeeze."),
        ("Wide-Grip Seated Cable Row", "🚣", "gym", False, "A seated cable row with a wide overhand bar to bias the upper back and rear delts — pull to the upper stomach with elbows flared and squeeze the mid-back at the finish."),
        ("Single-Arm Cable Row", "🚣", "gym", True, "A one-arm seated cable row that lets you rotate slightly for a bigger stretch and stronger lat contraction — pull the handle to your hip and control the reach forward."),
        ("Kroc Row", "🚣", "both", True, "A high-rep, heavy one-arm dumbbell row with a little controlled body English — brace on a bench, pull hard to the hip, and chase both load and reps to build a thick back and grip."),
        ("Gorilla Row", "🚣", "both", False, "Hinge over two kettlebells or dumbbells on the floor and row them alternately to your hips — the wide base and alternating pull hammer the lats while bracing the core."),
        ("Kettlebell Row", "🚣", "both", True, "A one-arm bent-over row with a kettlebell — the offset load challenges grip and lets the lat stretch deep at the bottom; brace the off hand and row to the hip."),
        ("Resistance Band Lat Pulldown", "🧗", "home", False, "Anchor a band overhead and pull both handles down to your shoulders while kneeling or seated — mimics a lat pulldown at home; drive the elbows down and squeeze the lats."),
        ("Seal Row", "🚣", "gym", False, "Lie face-down on a raised flat bench and row a barbell or dumbbells straight up to the underside — total chest support means zero cheating and a pure mid-back contraction."),
        ("Bench-Supported Dumbbell Row", "🚣", "both", True, "A one-arm dumbbell row with your free hand and knee braced on a bench — the support keeps the back flat so the working lat does all the pulling; row to the hip and squeeze."),
        ("Trap Bar Deadlift", "🏋️", "gym", False, "A deadlift standing inside a hex/trap bar with neutral-grip handles — the centered load is easier on the lower back and lets you lift heavy; drive through the floor and stand tall."),
        ("Deficit Deadlift", "🏋️", "gym", False, "A deadlift standing on a low platform so the bar starts below normal — the extra range builds strength off the floor; keep a flat back through the deeper stretch."),
        ("Snatch-Grip Deadlift", "🏋️", "gym", False, "A deadlift with a very wide grip that increases the range and loads the upper back and traps hard — keep the chest up and the bar close as you drive to lockout."),
        ("Block Pull", "🏋️", "gym", False, "A deadlift with the bar resting on blocks or in a rack just below the knee — trains lockout strength through a shortened range; pull from the dead stop with a braced back."),
        ("Kettlebell Deadlift", "🏋️", "both", False, "A deadlift lifting a kettlebell between your feet — a joint-friendly way to groove the hip hinge; push the hips back, keep the back flat, and stand tall by squeezing the glutes."),
        ("Hyperextension (Back Extension)", "🙇", "gym", False, "On a 45° or horizontal bench, hinge at the hips and raise your torso in line with your legs, squeezing the glutes and lower back — don't hyperextend past a straight line."),
        ("45-Degree Back Extension", "🙇", "gym", False, "On an angled hyperextension bench, bend at the hips and rise until your body forms a straight line — targets the glutes, hamstrings, and spinal erectors; add a plate to progress."),
        ("Reverse Hyperextension", "🙇", "gym", False, "Face-down on a bench or machine, swing your legs from hanging up to level behind you — trains the glutes and lower back with a gentle traction on the spine; control the swing."),
        ("Superman", "🙇", "home", False, "Lie face-down and simultaneously lift your arms, chest, and legs off the floor, squeezing the lower back and glutes — hold briefly at the top and lower with control."),
        ("Superman Hold", "🙇", "home", False, "The top of a Superman held as an isometric — arms and legs raised, back and glutes squeezed — building endurance in the spinal erectors; breathe and keep the neck neutral."),
        ("Bird Dog Row", "🚣", "both", True, "From a bird-dog position on a bench, row a dumbbell with one arm while bracing on the opposite knee — combines an anti-rotation core hold with a strict single-arm back row."),
        ("Inverted Row (Feet Elevated)", "🚣", "both", False, "A bodyweight row under a bar with your feet up on a box, making it harder — pull your chest to the bar with a rigid plank line and squeeze the shoulder blades."),
        ("Ring Row", "🚣", "both", False, "A bodyweight row hanging under gymnastic rings — the free-moving rings add a stability challenge; keep a straight body and pull until the rings reach your ribs."),
        ("TRX Row", "🚣", "both", False, "A suspension-trainer row: lean back on the straps and pull your chest to your hands, adjusting foot position to set the difficulty — keep the body rigid and squeeze the mid-back."),
        ("Snatch-Grip High Pull", "🚣", "gym", False, "Explosively pull a barbell from the hip up toward your collarbone with a wide grip and high elbows — a powerful trap and upper-back builder; drive with the hips, not the arms."),
        ("Chest-Supported T-Bar Row", "🚣", "gym", False, "A T-bar row with your chest braced on the machine's pad — the support kills lower-back strain and cheating, so the mid-back and lats do all the pulling; squeeze the shoulder blades at the top."),
    ],
    "Shoulders": [
        ("Seated Dumbbell Shoulder Press", "🏋️", "both", False, "Seated with back support, press two dumbbells overhead until the arms are nearly locked, then lower to ear level — the seat removes leg drive so the delts do the work."),
        ("Standing Dumbbell Shoulder Press", "🏋️", "both", False, "Press two dumbbells overhead from the shoulders while standing, bracing the core so you don't lean back — a strict overhead press that also trains full-body stability."),
        ("Seated Barbell Shoulder Press", "🏋️", "gym", False, "Seated, press a barbell from your upper chest to overhead in a straight line — the bench support lets you overload the delts; keep the ribs down and don't arch excessively."),
        ("Machine Shoulder Press", "🏋️", "gym", False, "A seated overhead press machine with a fixed path — press the handles up and slightly in, stopping short of lockout to keep the delts under tension; great for pushing to failure safely."),
        ("Smith Machine Shoulder Press", "🏋️", "gym", False, "An overhead press on the Smith machine's guided bar, seated or standing — the fixed track handles balance so you can focus on driving straight up and controlling the descent."),
        ("Push Press", "🏋️", "gym", False, "An overhead press using a slight dip and drive of the legs to launch the bar, then locking it out with the shoulders — lets you move heavier loads and builds overhead power."),
        ("Z Press", "🏋️", "gym", False, "An overhead press seated on the floor with legs straight out — the position removes all leg and back support, forcing a strict press and a very stable core; start light."),
        ("Behind-the-Neck Press", "🏋️", "gym", False, "A barbell overhead press lowered behind the head to the base of the neck — demands good shoulder mobility, so go light and only descend as far as stays comfortable."),
        ("Single-Arm Dumbbell Shoulder Press", "🏋️", "both", True, "A one-arm overhead press with a dumbbell — pressing one side adds an anti-lean core demand and evens out imbalances; keep the torso upright and don't tip toward the weight."),
        ("Single-Arm Landmine Press", "🏋️", "gym", True, "Press the end of a landmine barbell overhead and forward with one arm — the arc is shoulder-friendly and hits the front delt while the core resists rotation."),
        ("Bradford Press", "🏋️", "gym", False, "A barbell press alternating in front of and behind the head, never locking out — the constant tension torches the delts; use a light load and keep the reps smooth."),
        ("Dumbbell Lateral Raise", "🤸", "both", True, "Raise two dumbbells out to the sides to shoulder height with a slight elbow bend, leading with the elbows — the classic side-delt builder; control the lower and don't swing."),
        ("Seated Lateral Raise", "🤸", "both", True, "A lateral raise done seated to remove momentum — lift the dumbbells out to the sides strictly to shoulder height, pause, and lower slowly for maximum side-delt tension."),
        ("Leaning Cable Lateral Raise", "🤸", "gym", True, "Hold a post and lean away from a low cable, raising the handle out to the side — leaning increases the range and keeps tension on the side delt from the very bottom."),
        ("Machine Lateral Raise", "🤸", "gym", False, "A seated machine that pads against your upper arms as you raise them out to the sides — the fixed path isolates the side delts and is easy to push to failure."),
        ("Lu Raise", "🤸", "both", False, "Raise two dumbbells from your sides all the way overhead in a wide arc with straight-ish arms — a full-range side and front delt move; keep it light and controlled throughout."),
        ("Cable Front Raise", "🤸", "gym", True, "Raise a low-cable handle straight out in front to shoulder height — the cable keeps tension on the front delt through the whole range, unlike a dumbbell that unloads at the bottom."),
        ("Plate Front Raise", "🤸", "both", False, "Hold a weight plate at the edges and raise it straight out in front to eye level — a simple front-delt builder; keep the arms straight and avoid rocking the torso."),
        ("Dumbbell Front Raise", "🤸", "both", True, "Raise a dumbbell straight out in front to shoulder height, one arm at a time or together, to target the front delt — keep a slight elbow bend and don't use momentum."),
        ("Bent-Over Dumbbell Rear Delt Fly", "🦋", "both", False, "Hinge forward and open two dumbbells out to the sides with a soft elbow bend, squeezing the rear delts and upper back — lead with the elbows and don't let it turn into a row."),
        ("Seated Rear Delt Fly", "🦋", "both", False, "Seated and bent forward over your thighs, fly two dumbbells out to the sides to isolate the rear delts — the seated position kills momentum for a stricter contraction."),
        ("Cable Rear Delt Fly", "🦋", "gym", True, "Using a high or shoulder-height cable across the body, sweep the handle out and back to hit the rear delt with constant tension — squeeze the shoulder blade and control the return."),
        ("Reverse Pec Deck", "🦋", "gym", False, "Sit facing the pec-deck machine and open the handles out and back to target the rear delts and upper back — keep the chest against the pad and squeeze the shoulder blades together."),
        ("Rear Delt Row", "🚣", "both", False, "A high-elbow row (barbell, dumbbells, or cable) pulled to the upper chest with flared elbows to bias the rear delts and upper back over the lats — pause and squeeze at the top."),
        ("Cable Face Pull (Rope)", "😤", "gym", False, "Pull a rope from a high pulley toward your face, splitting the ends past your ears with the elbows high — a rear-delt and rotator-cuff staple for shoulder health; squeeze at the end."),
        ("Y-Raise", "🤸", "both", False, "Raise two light dumbbells up and out into a 'Y' overhead with thumbs up — targets the lower traps and rear/side delts; keep the arms straight and lift only as high as stays smooth."),
        ("Prone Y-Raise", "🤸", "both", False, "Face-down on an incline bench, raise two light dumbbells into a 'Y' overhead — strengthens the lower traps and posture muscles with strict, momentum-free reps."),
        ("W-Raise", "🤸", "both", False, "Face-down or leaning, pull two light dumbbells back into a 'W' shape by driving the elbows down and squeezing the shoulder blades — a rear-delt and lower-trap posture drill."),
        ("Cuban Press", "🏋️", "both", False, "A three-part move: upright-row the dumbbells up, externally rotate them so the forearms point up, then press overhead — a rotator-cuff and shoulder-health builder; go light."),
        ("Dumbbell Upright Row", "🚣", "both", True, "Pull two dumbbells straight up the front of the body to chest height with the elbows leading high — hits the side delts and traps; keep the lift to below the collarbone to spare the shoulders."),
        ("Cable Upright Row", "🚣", "gym", False, "Pull a low-cable bar or rope up the front of the body with high elbows — the cable keeps steady tension on the delts and traps; stop the pull at upper-chest height."),
        ("Wide-Grip Upright Row", "🚣", "gym", False, "An upright row with a wide barbell grip that biases the side delts over the traps and keeps the shoulders in a safer position — pull to chest height with the elbows out."),
        ("Dumbbell Shrug", "🤷", "both", True, "Hold a dumbbell in each hand and shrug the shoulders straight up toward your ears, squeezing the traps at the top, then lower fully — no rolling; just straight up and down."),
        ("Barbell Shrug", "🤷", "gym", False, "Hold a barbell at arm's length and shrug the shoulders up to your ears, pausing to squeeze the traps — keep the arms straight and avoid rolling the shoulders forward or back."),
        ("Cable Shrug", "🤷", "gym", False, "Shrug against a low cable or bar attachment — the constant tension keeps the traps loaded through the whole range; lift straight up, squeeze, and lower under control."),
        ("Trap Bar Shrug", "🤷", "gym", False, "Shrug while holding a loaded trap/hex bar — the neutral-grip, centered load lets you shrug heavy and safely; drive the shoulders straight up and pause at the top."),
        ("Behind-the-Back Barbell Shrug", "🤷", "gym", False, "Hold a barbell behind your glutes and shrug straight up — the rear position pulls the shoulders back and hits the traps with better posture; squeeze hard at the top."),
        ("Handstand Push-Up", "🤸", "home", False, "A vertical push-up kicked up against a wall — a bodyweight overhead press for the delts and triceps; lower under control until your head nears the floor, then press back up."),
        ("Wall Handstand Hold", "🧘", "home", False, "Kick up to a handstand against a wall and hold, building overhead and shoulder stability plus core control — keep the ribs down and press the floor away through the shoulders."),
        ("Pike Press (Deficit)", "🤸", "home", False, "A pike push-up with hands on raised blocks so your head drops below them — the added range makes it a tougher bodyweight overhead press for the shoulders; control the descent."),
        ("Landmine Lateral Raise", "🤸", "gym", True, "Raise the end of a landmine barbell out to the side with one arm — the fixed arc keeps steady tension on the side delt through a controlled range; alternate sides."),
        ("3-Way Shoulder Raise", "🤸", "both", False, "A giant set flowing front raise into lateral raise into bent-over rear raise with light dumbbells — hits all three delt heads in one continuous, high-tension sequence."),
        ("Cable Y-Raise", "🤸", "gym", False, "From low pulleys crossed in front, raise both handles up and out into a 'Y' overhead — the constant cable tension hits the side and rear delts plus lower traps; keep the arms long and thumbs up."),
    ],
    "Arms": [
        ("Incline Dumbbell Curl", "💪", "both", True, "Lie back on an incline bench and curl two dumbbells with the arms hanging behind the body — the stretched starting position hits the long head of the biceps hard; no swinging."),
        ("Seated Dumbbell Curl", "💪", "both", True, "Curl two dumbbells while seated to remove momentum — the strict position forces the biceps to lift the weight without help from the legs or a body swing."),
        ("Standing Dumbbell Curl", "💪", "both", True, "Curl two dumbbells from your sides up to your shoulders, keeping the elbows pinned — supinate (turn the pinky up) at the top for a full biceps contraction; lower slowly."),
        ("Alternating Dumbbell Curl", "💪", "both", False, "Curl one dumbbell at a time, alternating arms, so you can focus on each biceps in turn — keep the non-working arm still and avoid rocking the torso to swing the weight."),
        ("Cross-Body Hammer Curl", "🔨", "both", True, "Curl a dumbbell across your body toward the opposite shoulder with a neutral grip — targets the brachialis and forearm; keep the elbow tucked and alternate arms."),
        ("Incline Hammer Curl", "🔨", "both", True, "On an incline bench, curl two dumbbells with a neutral (palms-facing) grip from the stretched hanging position — hits the brachialis and outer arm with a big stretch."),
        ("Rope Hammer Curl", "🔨", "gym", False, "Curl a rope attachment on a low cable with a neutral grip, keeping the palms facing in — the constant cable tension builds the brachialis and forearms; squeeze at the top."),
        ("Dumbbell Preacher Curl", "💪", "both", True, "Curl one dumbbell with the back of your arm braced on a preacher bench pad — the fixed angle eliminates cheating and puts deep tension on the lower biceps; control the stretch."),
        ("Machine Preacher Curl", "💪", "gym", False, "A seated machine curl with the arms braced on a pad — the guided path isolates the biceps and is easy to push to failure; get a full stretch at the bottom and squeeze at the top."),
        ("Machine Bicep Curl", "💪", "gym", False, "A seated selectorized curl with the elbows fixed on a pad — the machine keeps the arms locked in position for strict, momentum-free biceps work through a full range."),
        ("Single-Arm Cable Curl", "💪", "gym", True, "Curl a single low-cable handle with one arm — the cable keeps tension on the biceps through the whole range, and going one side at a time evens out arm imbalances."),
        ("High Cable Curl", "💪", "gym", False, "Stand between two high pulleys and curl both handles toward your head like a front double-biceps pose — the overhead angle peaks the biceps contraction; squeeze hard."),
        ("Bayesian Cable Curl", "💪", "gym", True, "Face away from a low pulley and curl the handle with your arm behind the body — the constant-tension stretch position is one of the best long-head biceps builders."),
        ("Drag Curl", "💪", "both", False, "Curl a barbell or dumbbells by dragging them straight up the front of the body while the elbows travel back — a strict variation that keeps constant tension on the biceps."),
        ("Reverse Curl", "💪", "both", False, "Curl a barbell or dumbbells with an overhand (pronated) grip — shifts the work to the brachialis and forearm extensors for thicker, stronger-looking arms; keep the wrists firm."),
        ("Reverse EZ-Bar Curl", "💪", "gym", False, "A reverse (overhand) curl on an EZ-bar, whose angled grip is easier on the wrists — builds the forearms and brachialis; keep the elbows pinned and lift without swinging."),
        ("Cable Reverse Curl", "💪", "gym", False, "An overhand-grip curl on a low cable bar — the steady tension hammers the forearm extensors and brachialis; keep the wrists neutral and the elbows tight to the body."),
        ("21s Bicep Curl", "💪", "both", False, "A curl set of seven bottom-half reps, seven top-half reps, then seven full reps for 21 total — the extended time under tension gives the biceps a deep pump; use a lighter load."),
        ("Waiter Curl", "💪", "both", False, "Curl a single dumbbell held vertically by the top end in both cupped hands, like carrying a tray — the grip forces a strong biceps peak contraction; squeeze hard at the top."),
        ("Resistance Band Hammer Curl", "🔨", "home", True, "Stand on a band and curl the handles with a neutral grip — the band's rising tension peaks the brachialis contraction at the top; keep the elbows pinned and squeeze."),
        ("Isometric Bicep Hold", "💪", "both", False, "Hold a curl at the mid-range (elbow ~90°) with a challenging weight for time — the static contraction builds biceps strength and endurance; keep the elbow pinned and breathe."),
        ("Rope Tricep Pushdown", "💪", "gym", False, "Push a rope down from a high pulley, splitting the ends apart at the bottom and locking out the elbows — the rope split maximizes the triceps squeeze; keep the elbows tucked."),
        ("V-Bar Tricep Pushdown", "💪", "gym", False, "Push a V-bar down from a high pulley to full lockout — the fixed grip lets you load the triceps heavier than a rope; keep the elbows pinned to your sides throughout."),
        ("Single-Arm Tricep Pushdown", "💪", "gym", True, "A one-arm cable pushdown with a handle, often with an underhand grip — isolates each triceps and evens out imbalances; keep the elbow glued to your side and fully extend."),
        ("Reverse-Grip Tricep Pushdown", "💪", "gym", False, "A cable pushdown with an underhand (supinated) grip on a straight bar — biases the inner/medial head of the triceps; keep the wrists firm and the elbows locked in place."),
        ("Cable Overhead Tricep Extension", "💪", "gym", False, "Face away from a high or low pulley and extend a rope overhead until the arms lock out — the overhead angle stretches and works the long head of the triceps; keep the elbows narrow."),
        ("Dumbbell Overhead Tricep Extension", "💪", "both", True, "Hold a dumbbell overhead in one or both hands and lower it behind your head, then extend to lockout — the overhead stretch targets the long head; keep the elbows pointing forward."),
        ("Single-Arm Overhead Tricep Extension", "💪", "both", True, "Extend a single dumbbell overhead with one arm, lowering it behind the head and pressing to lockout — isolates each triceps and evens out imbalances; keep the elbow still and high."),
        ("EZ-Bar Overhead Extension", "💪", "gym", False, "Press an EZ-bar overhead and lower it behind your head, then extend to lockout — the angled grip is wrist-friendly and the overhead position loads the long head of the triceps."),
        ("Lying Dumbbell Tricep Extension", "💪", "both", False, "Lying on a bench, lower two dumbbells toward your forehead or beside your head, then extend to lockout — a dumbbell skull crusher that hits all three triceps heads; keep the elbows in."),
        ("Cable Skull Crusher", "💀", "gym", False, "Lying on a bench with a low cable, lower a bar or rope toward your forehead and extend — the cable keeps constant tension on the triceps that a barbell loses at lockout."),
        ("EZ-Bar Skull Crusher", "💀", "gym", False, "Lying down, lower an EZ-bar to your forehead or just behind your head by bending only the elbows, then extend — the angled bar spares the wrists; keep the upper arms still."),
        ("JM Press", "💪", "gym", False, "A hybrid of a close-grip bench and skull crusher — lower the bar toward your upper neck with the elbows tucked, then press back — a heavy triceps builder; start light to groove it."),
        ("Tate Press", "💪", "both", False, "Lying down, lower two dumbbells with the elbows flared so the weights come toward your chest, then extend — an unusual angle that hammers the outer triceps; keep it light and strict."),
        ("Tricep Dip (Bench, Weighted)", "🤾", "home", False, "A bench dip with feet elevated and a plate on your lap for added load — keep the elbows tucked and the torso upright to bias the triceps; lower until the elbows hit ~90°."),
        ("Tricep Kickback", "💪", "both", True, "Hinge forward, pin the upper arm to your side, and extend a dumbbell straight back to lockout — squeeze the triceps hard at the top; the peak contraction is the whole point, so go light."),
        ("Cable Tricep Kickback", "💪", "gym", True, "A one-arm kickback on a low cable — the constant tension keeps the triceps loaded even at full lockout, unlike a dumbbell; keep the upper arm pinned and horizontal."),
        ("Dumbbell Tricep Kickback", "💪", "both", True, "Braced on a bench, extend a dumbbell back from a pinned upper arm until the elbow locks out — a strict single-arm triceps isolation; squeeze and hold briefly at the top."),
        ("Katana Tricep Extension", "💪", "gym", True, "Face away from a high pulley and extend a single handle down and across your body like drawing a sword — a constant-tension single-arm triceps move; keep the elbow high and still."),
        ("Resistance Band Tricep Pushdown", "💪", "home", False, "Anchor a band up high and push the handles down to lockout — the band's tension peaks at full extension, squeezing the triceps hard; keep the elbows pinned to your sides."),
        ("Resistance Band Overhead Extension", "💪", "home", False, "Anchor a band low, face away, and extend the handles overhead to lockout — the overhead stretch and rising band tension load the long head of the triceps; keep the elbows narrow."),
        ("California Press", "💪", "gym", False, "A blend of a close-grip bench and a skull crusher: lower the bar to your chin/upper chest half like a skull crusher, then press out — a heavy, joint-friendly triceps builder."),
        ("Wrist Curl", "💪", "both", False, "Rest your forearms on your thighs or a bench with palms up and curl the weight using only the wrists — isolates the forearm flexors; use a full range and a light, controlled load."),
        ("Reverse Wrist Curl", "💪", "both", False, "Forearms braced with palms down, raise the weight using only the wrists — targets the forearm extensors for balanced, injury-resistant forearms; keep the movement slow and small."),
        ("Behind-the-Back Wrist Curl", "💪", "gym", False, "Hold a barbell behind your glutes and curl it with the wrists — the position gives the forearm flexors a bigger range than a standard wrist curl; keep it light and controlled."),
        ("Cable Wrist Curl", "💪", "gym", False, "Curl a low-cable bar using only the wrists with the forearms braced — the constant tension keeps the forearm flexors loaded throughout; slow and controlled beats heavy here."),
        ("Dumbbell Wrist Curl", "💪", "both", True, "A single-arm wrist curl with a dumbbell, forearm braced on your thigh — lets each forearm work independently through a full flex-and-extend range; keep it slow and light."),
        ("Farmer's Hold", "🧳", "both", False, "Hold a heavy dumbbell or kettlebell in each hand and simply stand tall for time — a static grip, forearm, and trap builder; keep the shoulders back and brace the core."),
        ("Plate Pinch Hold", "🧳", "both", False, "Pinch one or two smooth weight plates between your fingers and thumb and hold for time — a brutal grip and thumb-strength builder; set a target time and beat it each session."),
        ("Wrist Roller", "🔄", "both", False, "Roll a weight up on a cord wrapped around a bar or handle using only wrist rotation, then lower it — a classic forearm-burner; do it both directions for balanced grip strength."),
        ("Hand Gripper Squeeze", "💪", "home", False, "Squeeze a spring hand gripper closed for reps or holds — a simple, portable crushing-grip builder; work both hands evenly and control the release, don't let it snap open."),
        ("Fat-Grip Dumbbell Hold", "🧳", "both", False, "Wrap thick grips (or a towel) around a dumbbell handle and hold for time — the enlarged diameter massively increases the grip and forearm demand; keep the shoulders packed."),
        ("Towel Pull-Up Hold", "🧗", "both", False, "Drape a towel over a bar, grip an end in each hand, and hang or hold at the top of a pull-up — a savage grip and forearm challenge; keep the core tight and shoulders active."),
        ("Dead Hang", "🧗", "both", False, "Simply hang from a pull-up bar with straight arms for time — builds grip endurance and decompresses the shoulders and spine; keep the shoulders slightly active, not fully slack."),
        ("Finger Curl", "💪", "both", False, "Let a barbell or dumbbells roll to your fingertips, then curl them back into your palm using only the fingers — targets the deep grip and forearm flexors; keep the load light."),
        ("Spider Hammer Curl", "🔨", "gym", True, "Lean chest-down on an incline bench and curl a dumbbell with a neutral grip, the arm hanging straight down — the position kills momentum and hammers the brachialis; squeeze at the top."),
    ],
    "Legs": [
        ("High-Bar Back Squat", "🦵", "gym", False, "A back squat with the bar high on the traps and a more upright torso — biases the quads and keeps the knees tracking over the toes; descend to at least parallel and drive up."),
        ("Low-Bar Back Squat", "🦵", "gym", False, "A back squat with the bar lower across the rear delts and more forward hip lean — lets you lift heavier and shares load with the glutes and hamstrings; keep the back flat."),
        ("Smith Machine Squat", "🦵", "gym", False, "A squat on the Smith machine's guided bar — the fixed path removes balance so you can push the quads hard; place the feet slightly forward and descend to at least parallel."),
        ("Pause Squat", "🦵", "gym", False, "A back or front squat with a 2–3 second pause at the bottom — the dead stop kills the bounce and builds strength and control out of the hole; stay tight through the pause."),
        ("Tempo Squat", "🦵", "gym", False, "A squat with a deliberately slow descent (e.g. 3–4 seconds down) — the extended time under tension builds control and muscle; keep the same rigid brace the whole rep."),
        ("Safety Bar Squat", "🦵", "gym", False, "A squat using a padded safety-squat bar that sits on the shoulders with handles in front — easier on the shoulders and biases the upper back and quads; brace hard and stay upright."),
        ("Belt Squat", "🦵", "gym", False, "A squat with the load hanging from a hip belt instead of on your back — spares the spine while training the quads and glutes hard; great for high volume with no back fatigue."),
        ("Landmine Squat", "🦵", "gym", False, "Hold the end of a landmine barbell at your chest and squat — the arc keeps you upright and is very knee- and back-friendly; a great squat entry point or high-rep finisher."),
        ("Heels-Elevated Goblet Squat", "🍷", "both", False, "A goblet squat with the heels raised on plates or a wedge — the elevation lets you sit deeper and drives more quad activation; keep the torso tall and the dumbbell at your chest."),
        ("Cyclist Squat", "🦵", "gym", False, "A heels-elevated, narrow-stance squat that keeps the torso vertical to maximize quad tension — sit straight down over your midfoot; a favorite for building teardrop quad sweep."),
        ("Single-Leg Leg Press", "🦵", "gym", True, "A leg press performed one leg at a time — isolates each quad and glute, evens out imbalances, and reduces lower-back involvement; press through the whole foot and control the descent."),
        ("Reverse Hack Squat", "🦵", "gym", False, "Face into the hack-squat machine (chest against the pad) and squat — the reversed position biases the glutes and hamstrings while sparing the lower back; drive through the heels."),
        ("Machine Squat", "🦵", "gym", False, "A guided squat machine with a shoulder or hip pad — the fixed path lets beginners and high-rep sets load the quads and glutes safely with no balance demand."),
        ("Wall Sit", "🧘", "home", False, "Slide down a wall until your thighs are parallel to the floor and hold, knees over ankles — an isometric quad-burner; brace the core, keep the back flat on the wall, and hold for time."),
        ("Split Squat", "🦵", "both", True, "A stationary lunge: one foot forward, one back, lower straight down until the back knee nears the floor, then drive up — builds single-leg strength; keep the front knee tracking the toe."),
        ("Dumbbell Bulgarian Split Squat", "🦵", "both", True, "A rear-foot-elevated split squat holding dumbbells — the back foot on a bench forces the front leg to do the work, hammering the quad and glute; keep the torso tall and descend under control."),
        ("Deficit Reverse Lunge", "🚶", "both", True, "A reverse lunge stepping back off a raised platform so the front leg works through extra range — deepens the glute and quad stretch; keep the front knee stable and drive back up."),
        ("Dumbbell Walking Lunge", "🚶", "both", True, "Walk forward lunging with a dumbbell in each hand, alternating legs — a big unilateral quad and glute builder; take a controlled step, keep the torso tall, and drive through the front heel."),
        ("Barbell Walking Lunge", "🚶", "gym", True, "Walking lunges with a barbell on your back — the heavier load builds serious single-leg strength; step under control, keep the chest up, and don't let the front knee cave in."),
        ("Forward Lunge", "🚶", "both", True, "Step forward into a lunge until both knees hit ~90°, then push back to standing — trains the quads and glutes; keep the torso upright and the front knee tracking over the foot."),
        ("Lateral Lunge", "🚶", "both", True, "Step out wide to one side and sit back into that hip while the other leg stays straight — trains the quads, glutes, and adductors through a side plane; keep the chest up and push back to center."),
        ("Curtsy Lunge", "🚶", "both", True, "Step one leg back and across behind the other into a curtsy, then return — the crossover angle targets the glute medius and outer glute; keep the hips square and control the descent."),
        ("Front-Foot-Elevated Split Squat", "🦵", "both", True, "A split squat with the front foot on a small plate or step — the elevation increases the range and biases the glute and hamstring; keep the torso upright and descend under control."),
        ("Standing Leg Curl", "🦵", "gym", True, "Curl one heel toward your glute against a machine pad while standing — isolates each hamstring individually; squeeze at the top and lower slowly without swinging the leg."),
        ("Single-Leg Lying Leg Curl", "🦵", "gym", True, "A lying leg curl done one leg at a time to even out hamstring imbalances — curl the heel toward the glute, squeeze, and control the eccentric; keep the hips pinned to the pad."),
        ("Swiss Ball Leg Curl", "🦵", "both", False, "Lying on your back with heels on a stability ball, lift the hips and curl the ball toward you — a bodyweight hamstring and glute move; keep the hips high and control the roll-out."),
        ("Slider Leg Curl", "🦵", "home", False, "Lying on your back with heels on sliders (or towels on a smooth floor), bridge the hips and pull the heels toward you — a tough eccentric hamstring builder; keep the hips lifted."),
        ("Banded Leg Curl", "🦵", "home", True, "Anchor a band at your ankle and curl the heel toward your glute against its tension — a joint-friendly hamstring isolation you can do anywhere; squeeze at the top and resist the return."),
        ("Glute-Ham Raise", "🦵", "gym", False, "On a GHD, lower your torso forward from the knees under hamstring control, then pull back up — one of the best posterior-chain builders; keep the hips extended and the movement smooth."),
        ("Razor Curl", "🦵", "gym", False, "A GHD or bench hamstring curl where the hips flex slightly as you rise, keeping constant tension — a brutal hamstring finisher; control the lowering phase and don't rush."),
        ("Kettlebell Romanian Deadlift", "🏋️", "both", False, "A hip-hinge RDL holding a kettlebell (or two) — push the hips back with a flat back until you feel the hamstring stretch, then squeeze the glutes to stand; keep the weight close."),
        ("B-Stance Romanian Deadlift", "🏋️", "both", True, "An RDL with one foot staggered slightly back as a kickstand, loading mostly the front leg — a bridge between two-leg and single-leg hinges; hinge back and feel the working hamstring."),
        ("Cable Pull-Through", "🍑", "gym", False, "Face away from a low cable, straddle the rope, and hinge — push the hips back then snap them forward, squeezing the glutes — a hip-hinge pattern with constant glute tension."),
        ("Seated Good Morning", "🙇", "gym", False, "Seated with a barbell on your back, hinge your torso forward from the hips and return — trains the lower back and hamstrings with the legs taken out; keep a flat, braced spine."),
        ("Single-Leg Hip Thrust", "🍑", "both", True, "A hip thrust driving through one foot with the other leg raised — the single-leg load hammers each glute and exposes imbalances; squeeze hard at the top and keep the hips level."),
        ("Dumbbell Hip Thrust", "🍑", "both", False, "A hip thrust with a dumbbell across the hips, shoulders on a bench — drive through the heels to full hip extension and squeeze the glutes at the top; a great at-home glute builder."),
        ("Machine Hip Thrust", "🍑", "gym", False, "A dedicated hip-thrust machine with a padded lap bar — the fixed path lets you load the glutes heavy and safely; drive to full extension and pause with a hard glute squeeze."),
        ("Frog Pump", "🍑", "home", False, "Lying on your back with the soles of your feet together and knees splayed, pump the hips up and squeeze the glutes — the frog position biases the glutes over the hamstrings; go for reps."),
        ("Banded Glute Bridge", "🍑", "home", False, "A glute bridge with a mini-band above the knees, pushing the knees out as you lift — the band adds glute-medius activation; squeeze the glutes hard at the top of each rep."),
        ("B-Stance Hip Thrust", "🍑", "both", True, "A hip thrust with one foot staggered as a kickstand so most of the load goes through the front leg — a way to overload each glute without full single-leg balance; squeeze at the top."),
        ("Cable Glute Kickback", "🍑", "gym", True, "With an ankle strap on a low cable, drive one leg straight back and up, squeezing the glute — isolates each glute through a controlled range; keep the torso still and avoid arching the back."),
        ("Cable Hip Abduction", "🍑", "gym", True, "With an ankle strap on a low cable, lift one leg out to the side against the cable — targets the glute medius; keep the torso upright and control the return without swinging."),
        ("Banded Lateral Walk", "🍑", "home", False, "With a mini-band around the knees or ankles, step sideways in a half-squat, keeping tension the whole time — a glute-medius activator; stay low and don't let the knees cave in."),
        ("Banded Monster Walk", "🍑", "home", False, "With a band around the legs, step diagonally forward and out in a half-squat — fires up the glutes and hips; keep constant band tension and the knees pushed out throughout."),
        ("Standing Glute Kickback (Machine)", "🍑", "gym", True, "On a glute-kickback machine, drive one foot back against the pad to full hip extension — isolates each glute with a fixed path; squeeze at the top and control the return."),
        ("Step-Through Lunge", "🚶", "both", True, "Lunge forward, then without stopping step the same leg straight back into a reverse lunge — the continuous front-and-back motion torches the working quad and glute; keep the torso tall."),
        ("Kettlebell Sumo Deadlift", "🏋️", "both", False, "A wide-stance deadlift lifting a kettlebell between the legs — the sumo stance biases the glutes, inner thighs, and quads; push the hips forward to stand and keep the back flat."),
        ("Standing Calf Raise (Machine)", "🦶", "gym", False, "On a standing calf machine with the shoulders under the pads, rise onto the balls of your feet, pause at the top, and lower into a full stretch — train the full range for calf growth."),
        ("Smith Machine Calf Raise", "🦶", "gym", False, "A standing calf raise with the bar on your shoulders in a Smith machine and toes on a plate — the guided bar lets you load heavy; get a deep stretch at the bottom and a hard squeeze up top."),
        ("Leg Press Calf Raise", "🦶", "gym", False, "On the leg press with only the balls of your feet on the platform, press through the toes to full ankle extension and lower into a stretch — a safe way to load the calves heavy."),
        ("Single-Leg Calf Raise", "🦶", "both", True, "A calf raise on one foot, holding a dumbbell for load — the single-leg version exposes and fixes side-to-side imbalances; get a full stretch at the bottom and rise all the way up."),
        ("Donkey Calf Raise", "🦶", "gym", False, "Hinge at the hips with weight on your lower back or a machine pad and raise the heels — the bent-over position gives the calves a huge stretch; pause at the top and bottom."),
        ("Dumbbell Calf Raise", "🦶", "both", True, "A standing calf raise holding a dumbbell, one leg or two, with the toes on a plate for range — rise onto the balls of the feet, squeeze the calves, and lower into a full stretch."),
        ("Tibialis Raise", "🦶", "both", False, "With your back to a wall and heels forward, raise your toes toward your shins against bodyweight or a band — strengthens the shin muscle for knee health and jump/sprint resilience."),
        ("Seated Dumbbell Calf Raise", "🦶", "both", False, "Seated with a dumbbell on your knees and toes on a plate, raise the heels to work the soleus (deep calf) — the bent-knee position targets the lower calf; use a slow, full range."),
        ("Calf Press (Leg Press)", "🦶", "gym", False, "Push the leg-press platform with the balls of your feet only, extending the ankles fully — a heavy, back-safe calf builder; pause at full extension and lower into a deep stretch."),
        ("Copenhagen Plank", "🧘", "home", True, "A side plank with the top leg braced on a bench and the bottom leg lifting toward it — one of the best adductor (inner-thigh) strengtheners; keep the hips high and hold or do reps."),
        ("Jefferson Squat", "🦵", "gym", False, "Straddle a barbell and lift it with a staggered stance and mixed grip — an old-school squat/deadlift hybrid that trains the legs and core from an unusual angle; keep the back flat."),
        ("Anderson Squat", "🦵", "gym", False, "A squat starting from a dead stop with the bar on the rack's pins at the bottom — removes the stretch reflex to build raw strength out of the hole; drive up from a full stop."),
        ("Pin Squat", "🦵", "gym", False, "A squat descending to safety pins set at a target depth, pausing on them each rep — reinforces consistent depth and builds bottom-end strength; stay braced through the dead stop."),
        ("Goblet Box Squat", "🍷", "both", False, "A goblet squat sitting back to a box or bench each rep — the box teaches depth and hip loading and is very beginner-friendly; touch lightly and drive up without collapsing."),
        ("Eccentric Nordic Curl", "🦵", "both", False, "Kneeling with the ankles anchored, lower your torso forward as slowly as possible under hamstring control, then push off the floor to reset — a hamstring-strength and injury-prevention staple."),
        ("Reverse Nordic Curl", "🦵", "home", False, "Kneeling upright, lean your torso back from the knees under control while keeping the hips extended, then return — a big quad and knee-strength builder; only go as far as you can control."),
        ("Sumo Goblet Squat", "🍷", "both", False, "A goblet squat with a wide stance and toes turned out, holding a dumbbell or kettlebell at the chest — the sumo stance biases the glutes and inner thighs; sit straight down and drive up tall."),
    ],
    "Core": [
        ("Hanging Knee Raise", "🦵", "both", False, "Hang from a bar and raise your knees toward your chest, curling the pelvis up rather than just swinging the legs — control the lower and don't let momentum kip you; a lower-ab staple."),
        ("Hanging Windshield Wiper", "🌀", "both", False, "Hang from a bar, raise the legs, and sweep them side to side like wipers — an advanced obliques and lower-ab move; keep the movement controlled and the shoulders active."),
        ("Toes-to-Bar", "🦵", "both", False, "Hang from a bar and raise your straight legs until your toes touch it — a full-range lower-ab and hip-flexor move; control the descent and avoid excessive swinging."),
        ("Captain's Chair Leg Raise", "🦵", "gym", False, "In a captain's-chair station with forearms on the pads, raise your knees or straight legs toward your chest — the back support isolates the abs; curl the pelvis and lower slowly."),
        ("Lying Leg Raise", "🦵", "home", False, "Lying flat, raise your straight legs to vertical then lower them without letting the lower back arch off the floor — a lower-ab builder; press the low back down throughout."),
        ("Reverse Crunch", "🌀", "home", False, "Lying on your back, curl your knees and hips up toward your chest, lifting the tailbone off the floor — targets the lower abs; use control, not momentum, and don't yank with the legs."),
        ("Weighted Crunch", "🌀", "both", False, "A crunch holding a plate or dumbbell on your chest — the added load builds the upper abs; curl the ribcage toward the pelvis and squeeze, then lower under control."),
        ("Decline Sit-Up", "🌀", "gym", False, "A full sit-up on a decline bench with feet anchored — the angle increases the range and difficulty; curl up smoothly and lower with control, adding a plate to progress."),
        ("Low-to-High Cable Chop", "🪓", "gym", False, "From a low pulley, pull the handle diagonally up and across your body to the opposite shoulder, rotating through the core — a standing obliques and anti-rotation builder; keep the arms long."),
        ("High-to-Low Cable Chop", "🪓", "gym", False, "From a high pulley, pull the handle diagonally down and across to the opposite hip, rotating through the trunk — trains the obliques through a chopping pattern; control the return."),
        ("Landmine Rotation", "🪓", "gym", False, "Hold the end of a landmine barbell at arm's length and arc it side to side across your body, rotating through the hips and core — a powerful rotational obliques move; keep the arms straight."),
        ("Standing Cable Crunch", "🌀", "gym", False, "Facing a high pulley with a rope behind your head, crunch your ribcage down toward your pelvis — the cable keeps constant tension on the abs; round the spine, don't just hinge at the hips."),
        ("Weighted Plank", "🧘", "both", False, "A forearm plank with a plate on your back for added load — brace the whole body in a straight line and hold for time; the extra weight builds serious core stiffness."),
        ("Plank Shoulder Tap", "🧘", "home", False, "In a high plank, tap each hand to the opposite shoulder while keeping the hips completely still — the anti-rotation demand hits the deep core; move slowly and don't let the hips sway."),
        ("RKC Plank", "🧘", "home", False, "A forearm plank cranked to maximum tension: squeeze the glutes, quads, and abs as hard as possible and hold — a short, intense full-body brace; 10–20 seconds is plenty."),
        ("Long-Lever Plank", "🧘", "home", False, "A forearm plank with the elbows placed further forward than usual, lengthening the lever — dramatically increases the ab demand; keep the hips level and hold only as long as form holds."),
        ("Side Plank with Reach-Through", "🧘", "home", True, "From a side plank, rotate and thread the top arm under your body, then reach it back to the sky — trains the obliques dynamically; keep the hips high and the motion controlled."),
        ("Star Plank", "🧘", "home", False, "A side plank with the top arm and top leg both raised into a star shape — a tough obliques and hip-stability hold; keep the body in one line and the hips lifted."),
        ("Hollow Body Hold", "🧘", "home", False, "Lying on your back, press the low back into the floor and lift the shoulders and legs into a shallow 'banana' shape — a foundational core-tension hold; keep the ribs down and hold for time."),
        ("Hollow Body Rock", "🌀", "home", False, "From a hollow-body position, rock gently back and forth as one rigid piece — the rocking adds a dynamic challenge to the core brace; keep the low back glued down throughout."),
        ("Flutter Kick", "🌀", "home", False, "Lying on your back with legs straight and slightly raised, alternately kick them up and down in small, fast scissoring motions — a lower-ab and hip-flexor burner; keep the low back pressed down."),
        ("Scissor Kick", "🌀", "home", False, "Lying on your back with legs raised, cross them over and under each other in a scissoring motion — targets the lower abs and inner thighs; keep the low back flat and the movement controlled."),
        ("Toe Touch Crunch", "🌀", "home", False, "Lying on your back with legs straight up, reach your hands toward your toes by crunching the upper abs — a strict upper-ab move; lift the shoulder blades off the floor and lower slowly."),
        ("Heel Tap", "🌀", "home", False, "Lying with knees bent and shoulders slightly raised, crunch side to side to tap each heel with the same-side hand — a simple oblique burner; keep the shoulders off the floor throughout."),
        ("Medicine Ball Russian Twist", "🏐", "both", False, "Seated and leaning back with the feet up, rotate a medicine ball from hip to hip, following it with your eyes — a loaded rotational obliques move; keep the chest up and move under control."),
        ("Standing Ab Wheel Rollout", "🎡", "both", False, "From a standing bent-over position, roll an ab wheel out until your body is nearly horizontal, then pull back — the standing version is an advanced anti-extension challenge; keep the core braced."),
        ("Stir-the-Pot", "🏐", "both", False, "In a plank with forearms on a stability ball, draw small circles with the forearms — the moving base forces the deep core to fight rotation and extension; keep the hips and spine still."),
        ("L-Sit Hold", "🧘", "both", False, "Supported on parallettes or the floor, lift your body with straight legs held out in front to form an 'L' and hold — a serious core and hip-flexor isometric; start with tucked knees to build up."),
        ("Dragon Flag", "🌀", "both", False, "Lying on a bench gripping behind your head, raise your whole body to near-vertical then lower it straight and rigid — a legendary advanced core move; keep the body in one line and control the descent."),
        ("Half-Kneeling Pallof Press", "🎗️", "gym", True, "In a half-kneeling stance beside a cable, press the handle straight out and resist its pull toward the machine — an anti-rotation core exercise; keep the hips square and don't let the torso twist."),
        ("Hanging Oblique Raise", "🌀", "both", False, "Hang from a bar and raise your knees up and out to one side, then the other — the diagonal curl targets the obliques and lower abs; control the swing and keep the shoulders active."),
    ],
    "Full Body / Conditioning": [
        ("Power Clean", "🏋️", "gym", False, "Explosively pull a barbell from the floor and catch it on the front of the shoulders in a partial squat — a full-body power move; drive with the hips and receive the bar with soft knees."),
        ("Hang Clean", "🏋️", "gym", False, "A power clean starting from the hang (bar at the hips) rather than the floor — teaches the explosive hip drive and catch; snap the hips and pull yourself under the bar."),
        ("Power Snatch", "🏋️", "gym", False, "Explosively pull a barbell from the floor overhead to a locked-out catch in one motion with a wide grip — the most explosive full-body lift; drive with the hips and punch the bar up."),
        ("Hang Snatch", "🏋️", "gym", False, "A power snatch starting from the hang at the hips — grooves the fast hip extension and overhead catch without the floor pull; keep the bar close and lock out overhead."),
        ("Clean Pull", "🏋️", "gym", False, "The pulling portion of a clean without the catch: explosively extend the hips and shrug the bar up to the waist/chest — builds power and pulling strength; finish tall on the toes."),
        ("Dumbbell Clean and Press", "🏋️", "both", False, "Explosively pull two dumbbells to the shoulders, then press them overhead — a full-body strength and conditioning move; drive with the hips on the clean and brace hard on the press."),
        ("Dumbbell Snatch", "🏋️", "both", True, "Explosively pull a single dumbbell from between the feet to a locked-out position overhead in one motion — a full-body power and conditioning staple; alternate arms and drive with the hips."),
        ("Kettlebell Clean", "🔔", "both", True, "Swing a kettlebell up and rotate the hand around it to catch it softly in the rack position at the shoulder — the foundation of most kettlebell complexes; guide it, don't let it bang the forearm."),
        ("Kettlebell Clean and Press", "🔔", "both", True, "Clean a kettlebell to the shoulder, then press it overhead — a full-body strength builder that trains the hips, shoulders, and core in one movement; keep the wrist straight and press strict."),
        ("Kettlebell Snatch", "🔔", "both", True, "Swing a kettlebell overhead in one explosive motion, punching the hand through at the top to catch it softly — a high-power conditioning move; drive with the hips and control the receive."),
        ("Kettlebell Goblet Squat", "🍷", "both", False, "Hold a kettlebell at your chest by the horns and squat between your knees — a beginner-friendly, upright squat that hits the quads, glutes, and core; sit deep and drive through the heels."),
        ("Man Maker", "🏋️", "both", False, "A brutal combo: renegade rows, a push-up, a clean, and an overhead press with two dumbbells in one sequence — full-body strength and conditioning; keep the core braced through every phase."),
        ("Dumbbell Thruster", "🏋️", "both", False, "Front-squat two dumbbells at the shoulders, then drive up and press them overhead in one fluid motion — a full-body strength-and-cardio move; use the leg drive to launch the press."),
        ("Wall Walk", "🤸", "home", False, "From a push-up on the floor facing away from a wall, walk your feet up the wall and hands in toward it into a handstand, then reverse — a full-body shoulder and core builder; move slowly."),
        ("Bear Complex", "🏋️", "gym", False, "A barbell chain of power clean, front squat, push press, back squat, and second push press done unbroken — a savage full-body conditioning circuit; keep the reps crisp and the core braced."),
        ("Barbell Complex", "🏋️", "gym", False, "A sequence of barbell lifts (e.g. row, clean, front squat, press, back squat) done back-to-back without setting the bar down — builds strength-endurance; pick a weight the weakest lift can handle."),
        ("Sandbag Get-Up", "🎒", "both", False, "Hug a sandbag to your chest and stand up from the floor and back down, repeatedly — a rugged full-body and core builder that mimics real-world lifting; keep the bag tight and the back flat."),
    ],
}


def _build():
    out = []
    for category, items in _BY_CATEGORY.items():
        for name, emoji, location, unilateral, description in items:
            out.append({
                "name": name,
                "category": category,
                "emoji": emoji,
                "location": location,
                "unilateral": unilateral,
                "description": description,
            })
    return out


EXTRA_EXERCISES = _build()
